# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/i7219595/SimpleNGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/i7219595/SimpleNGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/i7219595/SimpleNGL/CMakeFiles /home/i7219595/SimpleNGL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/i7219595/SimpleNGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimpleNGL

# Build rule for target.
SimpleNGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleNGL
.PHONY : SimpleNGL

# fast build rule for target.
SimpleNGL/fast:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/build
.PHONY : SimpleNGL/fast

#=============================================================================
# Target rules for targets named SimpleNGL_automoc

# Build rule for target.
SimpleNGL_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleNGL_automoc
.PHONY : SimpleNGL_automoc

# fast build rule for target.
SimpleNGL_automoc/fast:
	$(MAKE) -f CMakeFiles/SimpleNGL_automoc.dir/build.make CMakeFiles/SimpleNGL_automoc.dir/build
.PHONY : SimpleNGL_automoc/fast

SimpleNGL_automoc.o: SimpleNGL_automoc.cpp.o

.PHONY : SimpleNGL_automoc.o

# target to build an object file
SimpleNGL_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/SimpleNGL_automoc.cpp.o
.PHONY : SimpleNGL_automoc.cpp.o

SimpleNGL_automoc.i: SimpleNGL_automoc.cpp.i

.PHONY : SimpleNGL_automoc.i

# target to preprocess a source file
SimpleNGL_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/SimpleNGL_automoc.cpp.i
.PHONY : SimpleNGL_automoc.cpp.i

SimpleNGL_automoc.s: SimpleNGL_automoc.cpp.s

.PHONY : SimpleNGL_automoc.s

# target to generate assembly for a file
SimpleNGL_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/SimpleNGL_automoc.cpp.s
.PHONY : SimpleNGL_automoc.cpp.s

src/NGLScene.o: src/NGLScene.cpp.o

.PHONY : src/NGLScene.o

# target to build an object file
src/NGLScene.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/src/NGLScene.cpp.o
.PHONY : src/NGLScene.cpp.o

src/NGLScene.i: src/NGLScene.cpp.i

.PHONY : src/NGLScene.i

# target to preprocess a source file
src/NGLScene.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/src/NGLScene.cpp.i
.PHONY : src/NGLScene.cpp.i

src/NGLScene.s: src/NGLScene.cpp.s

.PHONY : src/NGLScene.s

# target to generate assembly for a file
src/NGLScene.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/src/NGLScene.cpp.s
.PHONY : src/NGLScene.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleNGL.dir/build.make CMakeFiles/SimpleNGL.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SimpleNGL_automoc"
	@echo "... SimpleNGL"
	@echo "... SimpleNGL_automoc.o"
	@echo "... SimpleNGL_automoc.i"
	@echo "... SimpleNGL_automoc.s"
	@echo "... src/NGLScene.o"
	@echo "... src/NGLScene.i"
	@echo "... src/NGLScene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

