Cebitor Class Reference
CEB text editor class inherits from QsciScintilla.
#include <Cebitor.h>
Public Types
enum MarkerType { ERROR,
WARNING
 }
Enum for supported marker types.
Public Slots
void clearErrors ()
Removes all error and warning line markers.
void searchNext ()
Search for next occurance.
void searchPrev ()
Search for previous occurance.
void highlightAllSearch ()
sets indicator for each search result
void highlightAllSearch (const QString &_text)
sets indicator for each search result
Public Member Functions
Cebitor (QWidget *_parent)
Cebitor constructor, initialises default values.
void setSearchWidget (QWidget *_searchWidget)
stores widget containing the searchbar
void setSearchLineEdit (QLineEdit *_searchLineEdit)
stores QLineEdit widget from the searchbar
Protected Slots
void comment ()
comment out all selected lines
void toggleSearchBox ()
toggle search widget
void charAdded (const int _c)
called when a character is added
void resetHighlightColour ()
reset the highlighting colour
Protected Member Functions
bool autoClose (const QString _close)
adds closing character for braces and quotes
bool closing (const QString _close)
removes duplicates of closing braces and quotes
void braceIndent ()
adds indentation after newline following a `{`
Protected Attributes
QWidget * m_searchWidget
widget containing the searchbar
QLineEdit * m_searchLineEdit
searchbar QLineEdit widget
std::vector< int > m_fileMarkers
vector of all line markers
int m_searchIndicator
indicator used to highlight all search terms
Detailed Description
CEB text editor class inherits from QsciScintilla.
Definition at line 22 of file Cebitor.h.
Member Enumeration Documentation
enum Cebitor::MarkerType
Enum for supported marker types.
Enumerator
ERROR
 Symbol marker for Errors.
WARNING
 Symbol marker for warnings.
Definition at line 30 of file Cebitor.h.
  {
    ERROR,
    WARNING,
  };
Constructor & Destructor Documentation
Cebitor::Cebitor (QWidget * _parent)
Cebitor constructor, initialises default values.
Bug
Bug brace matching matches `<` and `>` characters
Definition at line 23 of file Cebitor.cpp.
References charAdded(), comment(), m_searchIndicator, resetHighlightColour(), and toggleSearchBox().
                                 : QsciScintilla(_parent)
{
  setMinimumHeight(300);
  // Create and assign the lexer
  QsciLexer* lex = new QsciLexerGLSL(this);
  setLexer(lex);
  // Set the margin defaults
  setMarginType(0,MarginType::NumberMargin);
  setMarginWidth(0," 012");
  setMarginsForegroundColor(QColor(128, 128, 128));
  // Set the symbol margin defaults
  setMarginType(1,MarginType::SymbolMargin);
  setMarginWidth(1,12);
  setMarginMarkerMask(1,
                      1 << MarkerType::ERROR |
                      1 << MarkerType::WARNING
                      );
  // Set the caret defaults
  setCaretForegroundColor(QColor(247, 247, 241));
  setCaretWidth(2);
  // Set the brace defaults
  //----------------------------------------------------------------------------
  //----------------------------------------------------------------------------
  setBraceMatching(BraceMatch::SloppyBraceMatch);
  setMatchedBraceBackgroundColor(QColor(62, 61, 50));
  setUnmatchedBraceBackgroundColor(QColor(249, 38, 114));
  // Set auto-indent
  setAutoIndent(true);
  setIndentationsUseTabs(false);
  setIndentationWidth(2);
  // Enable scroll width tracking and set the scroll width to a low number
  // Scintilla doesn't track line length, so if we wanted automated scrollbar
  // to appear we would need to implement a line length checking
  SendScintilla(QsciScintillaBase::SCI_SETSCROLLWIDTHTRACKING, 1);
  SendScintilla(QsciScintillaBase::SCI_SETSCROLLWIDTH, 5);
  // set up line markers
  QIcon errorIcon = QIcon::fromTheme(QString("dialog-error"));
  QIcon warnIcon = QIcon::fromTheme(QString("dialog-warning"));
  markerDefine(errorIcon.pixmap(10,10), MarkerType::ERROR);
  markerDefine(warnIcon.pixmap(10,10), MarkerType::WARNING);
  // unbind CTRL-/ keyboard shortcut
  standardCommands()->boundTo(Qt::Key_Slash | Qt::CTRL)->setKey(0);
  // rebind CTRL-/ to comment function
  QAction *commentAction = new QAction(this);
  commentAction->setShortcut(Qt::Key_Slash | Qt::CTRL);
  connect(commentAction, SIGNAL(triggered()), this, SLOT(comment()));
  addAction(commentAction);
  // bind CTRL-F to search function
  QAction *searchAction = new QAction(this);
  searchAction->setShortcut(Qt::Key_F | Qt::CTRL);
  connect(searchAction, SIGNAL(triggered()), this, SLOT(toggleSearchBox()));
  addAction(searchAction);
  // define search indicator
  m_searchIndicator = indicatorDefine(IndicatorStyle::PlainIndicator, -1);
  setIndicatorDrawUnder(true, m_searchIndicator);
  setIndicatorForegroundColor(QColor(142,143,137,0));
  setIndicatorOutlineColor(QColor(142,143,137,255));
  // connect char added signals and slots
  connect(this, SIGNAL(SCN_CHARADDED(int)), this, SLOT(charAdded(int)));
  // work-around since using built-in focusInEvent causes caret to be invisible
  connect(this, SIGNAL(SCN_FOCUSIN()), this, SLOT(resetHighlightColour()));
}
Member Function Documentation
bool Cebitor::autoClose (const QString _close) [protected]
adds closing character for braces and quotes
Parameters
in _close closing character
Returns
true if closing character is added
Definition at line 177 of file Cebitor.cpp.
{
  int cursorIndex;
  int cursorLine;
  int length;
  getCursorPosition(&cursorLine, &cursorIndex);
  length = lineLength(cursorLine);
  // special case for if cursor is on last line since in has no EOL
  if (cursorLine == lines()-1) { length++; }
  // insert closing character if cursor is at EOL or the next character is space
  if(cursorIndex == length-1 ||
     text(cursorLine).at(cursorIndex).toLatin1() == ' ')
  {
    insert(_close);
    return true;
  }
  return false;
}
void Cebitor::braceIndent () [protected]
adds indentation after newline following a `{`
Definition at line 323 of file Cebitor.cpp.
{
  int cursorIndex;
  int cursorLine;
  QString currentLine;
  QString previousLine;
  getCursorPosition(&cursorLine, &cursorIndex);
  currentLine = text(cursorLine);
  previousLine = text(cursorLine-1);
  // indent if previous line ends with "{"
  if(previousLine.endsWith("{\n"))
  {
    int indentSize;
    indentSize = indentation(cursorLine-1);
    setIndentation(cursorLine, indentSize+indentationWidth());
    cursorIndex = cursorIndex+indentationWidth();
    setCursorPosition(cursorLine, cursorIndex);
    currentLine = text(cursorLine);
    // extra newline to separate "{}"
    if(currentLine.indexOf("}") == cursorIndex)
    {
      insert(QString("\n"));
    }
  }
  // unindent if "}" after cursor
  else if(currentLine.indexOf("}") == cursorIndex)
  {
    int indentSize;
    indentSize = indentation(cursorLine)-indentationWidth();
    if(indentSize < 0)
    {
      indentSize = 0;
    }
    setIndentation(cursorLine, indentSize);
  }
}
void Cebitor::charAdded (const int _c) [protected], [slot]
called when a character is added
Definition at line 364 of file Cebitor.cpp.
References autoClose(), braceIndent(), and closing().
{
  switch(_c)
  {
    case (int) '(': { autoClose(QString(')')); break; }
    case (int) '{': { autoClose(QString('}')); break; }
    case (int) '[': { autoClose(QString(']')); break; }
    case (int) ')': { closing(QString(')')); break; }
    case (int) '}': { closing(QString('}')); break; }
    case (int) ']': { closing(QString(']')); break; }
    // special case since " opens and closes
    case (int) '"':
    {
      if(!closing(QString('"')))
      {
        autoClose(QString('"'));
      }
      break;
    }
    // auto indent for braces
    case (int) '\n': { braceIndent(); break; }
  }
}
void Cebitor::clearErrors () [slot]
Removes all error and warning line markers.
Definition at line 104 of file Cebitor.cpp.
{
  markerDeleteAll(MarkerType::ERROR);
  markerDeleteAll(MarkerType::WARNING);
}
bool Cebitor::closing (const QString _close) [protected]
removes duplicates of closing braces and quotes
Parameters
in _close closing character
Returns
true if duplicate character is replaced
Definition at line 199 of file Cebitor.cpp.
{
  int cursorIndex;
  int cursorLine;
  getCursorPosition(&cursorLine, &cursorIndex);
  int length = lineLength(cursorLine);
  // special case for if cursor is last position in file
  if(cursorLine == lines()-1 && length == cursorIndex)
  {
    return false;
  }
  // remove duplicate if next character is the same as _close
  if(text(cursorLine).at(cursorIndex) == _close.at(0))
  {
    setSelection(cursorLine, cursorIndex, cursorLine, cursorIndex+1);
    removeSelectedText();
    return true;
  }
  // auto unindent "}"
  if(_close == QString('}') && cursorIndex == indentation(cursorLine)+1)
  {
    int indentSize;
    indentSize = indentation(cursorLine)-indentationWidth();
    if(indentSize < 0)
    {
      indentSize = 0;
    }
    setIndentation(cursorLine, indentSize);
  }
  return false;
}
void Cebitor::comment () [protected], [slot]
comment out all selected lines
Definition at line 235 of file Cebitor.cpp.
{
  beginUndoAction();
  int lineFrom;
  int indexFrom;
  int lineTo;
  int indexTo;
  // get selected lines or current line if no text is selected
  if(hasSelectedText())
  {
    getSelection(&lineFrom, &indexFrom, &lineTo, &indexTo);
  }
  else
  {
    getCursorPosition(&lineFrom, &indexFrom);
    lineTo = lineFrom;
    indexTo = indexFrom;
  }
  // check if selected lines are already commented
  bool alreadyCommented = true;
  for(int i=lineFrom; i<=lineTo; i++)
  {
    QString lineText = text(i);
    if(!lineText.startsWith("//"))
    {
      alreadyCommented = false;
    }
  }
  // remove "//" from each line if they are already commented
  if(alreadyCommented)
  {
    for(int i=lineFrom; i<=lineTo; i++)
    {
      setSelection(i,0,i,2);
      removeSelectedText();
    }
    //offset original selection for reselecting text
    indexTo -= 2;
    if(indexFrom > 1)
    {
      indexFrom -= 2;
    }
  }
  // insert "//" at the start of each line
  else
  {
    for(int i=lineFrom; i<=lineTo; i++)
    {
      insertAt(QString("//"),i,0);
    }
    //offset original selection for reselecting text
    indexTo += 2;
    if(indexFrom != 0)
    {
      indexFrom += 2;
    }
  }
  // reselect to match original selection
  setSelection(lineFrom,indexFrom,lineTo,indexTo);
  endUndoAction();
}
void Cebitor::highlightAllSearch () [slot]
sets indicator for each search result
Definition at line 146 of file Cebitor.cpp.
References m_searchIndicator, and m_searchLineEdit.
{
  clearIndicatorRange(0,0,lines(),text(lines()).length(),m_searchIndicator);
  int line;
  int indexFrom;
  int indexTo;
  QString searchTerm = m_searchLineEdit->text();
  if(searchTerm.length()==0)
  {
    return;
  }
  int current;
  current = text().indexOf(
        searchTerm,
        0,
        Qt::CaseSensitivity::CaseInsensitive
        );
  while(current!= -1)
  {
    lineIndexFromPosition(current,&line,&indexFrom);
    indexTo = indexFrom + searchTerm.length();
    fillIndicatorRange(line,indexFrom,line,indexTo,m_searchIndicator);
    current = text().indexOf(searchTerm,
                             current+1,
                             Qt::CaseSensitivity::CaseInsensitive
                             );
  }
}
void Cebitor::highlightAllSearch (const QString & _text) [slot]
sets indicator for each search result
Parameters
in _text the text that has been changed
Definition at line 140 of file Cebitor.cpp.
References highlightAllSearch().
{
  highlightAllSearch();
}
void Cebitor::resetHighlightColour () [protected], [slot]
reset the highlighting colour
Definition at line 393 of file Cebitor.cpp.
{
  setSelectionBackgroundColor(QColor(61,61,52));
  resetSelectionForegroundColor();
}
void Cebitor::searchNext () [slot]
Search for next occurance.
Definition at line 110 of file Cebitor.cpp.
References m_searchLineEdit.
{
  QString searchTerm = m_searchLineEdit->text();
  bool found;
  found = findFirst(searchTerm, false, false, false, true);
  if(found)
  {
    setSelectionBackgroundColor(QColor(230, 219, 116));
    setSelectionForegroundColor(QColor(39,40,34));
  }
}
void Cebitor::searchPrev () [slot]
Search for previous occurance.
Definition at line 124 of file Cebitor.cpp.
References m_searchLineEdit.
{
  QString searchTerm = m_searchLineEdit->text();
  bool found;
  found = findFirst(searchTerm, false, false, false, true, false);
  if(found)
  {
    findNext();
    setSelectionBackgroundColor(QColor(230, 219, 116));
    setSelectionForegroundColor(QColor(39,40,34));
  }
  findNext();
}
void Cebitor::setSearchLineEdit (QLineEdit * _searchLineEdit) [inline]
stores QLineEdit widget from the searchbar
Definition at line 49 of file Cebitor.h.
References m_searchLineEdit.
                                {
                                  m_searchLineEdit = _searchLineEdit;
                                }
void Cebitor::setSearchWidget (QWidget * _searchWidget) [inline]
stores widget containing the searchbar
Definition at line 42 of file Cebitor.h.
References m_searchWidget.
                              {
                                m_searchWidget = _searchWidget;
                              }
void Cebitor::toggleSearchBox () [protected], [slot]
toggle search widget
Definition at line 303 of file Cebitor.cpp.
References highlightAllSearch(), m_searchIndicator, m_searchLineEdit, and m_searchWidget.
{
  bool searchFocus = m_searchLineEdit->hasFocus();
  if(!searchFocus)
  {
    connect(this,SIGNAL(textChanged()),this,SLOT(highlightAllSearch()));
    m_searchWidget->show();
    m_searchLineEdit->setFocus();
  }
  else
  {
    disconnect(this,SIGNAL(textChanged()),this,SLOT(highlightAllSearch()));
    m_searchWidget->hide();
    setFocus();
    clearIndicatorRange(0,0,lines(),text(lines()).length(),m_searchIndicator);
  }
}
Member Data Documentation
std::vector<int> Cebitor::m_fileMarkers [protected]
vector of all line markers
Definition at line 90 of file Cebitor.h.
int Cebitor::m_searchIndicator [protected]
indicator used to highlight all search terms
Definition at line 94 of file Cebitor.h.
QLineEdit* Cebitor::m_searchLineEdit [protected]
searchbar QLineEdit widget
Definition at line 86 of file Cebitor.h.
QWidget* Cebitor::m_searchWidget [protected]
widget containing the searchbar
Definition at line 82 of file Cebitor.h.
The documentation for this class was generated from the following files:
Cebitor.h
Cebitor.cpp