Button Class Reference
Parent class of different button types to set uniform values.
#include <Button.h>
Public Member Functions
Button (QWidget *parent=0)
default constructor to create the button
Button (QString _buttonName, GLenum _buttonType, QLayout *_layout, GLuint _id, ButtonLib *_libParent, NGLScene *_sceneParent, QWidget *parent=0)
constructor to create the button, custom variables can also be assigned
QString getName ()
returns the current button name
GLenum getTypeEnum ()
returns the current button type
void setID (unsigned int _id)
sets the current ID for the button, from its' shader location
GLuint getID ()
returns the button ID, this will change based on shader location
virtual void setColour (ngl::Vec4 _col)
sets the colour to be used by colour buttons
virtual void setColour (QColor _col)
overloaded function to set the colour
virtual ngl::Vec4 getColour ()
returns the colour, stored by the button
virtual QColor getColourQ ()
returns the QColour, stored by the button
virtual void setValue (float _val)
sets the value to be for float attributes
virtual float getValue ()
returns the value, stored by the button
virtual void printValues ()
prints the button attribute values
virtual ngl::Vec4 getVec ()
returns the Vec4 held by the vector button class
virtual void setVec (ngl::Vec4 _value)
sets the vector value for Vec3s or positions
Public Attributes
ButtonLib * m_libParent
pointer to the button library parent
NGLScene * m_sceneParent
pointer to the scene so that update can be called
QWidget * m_parent
pointer to the parent window to know where to attach to
QPushButton * m_button
button object to be pressed by user to open relevant widget
Private Slots
virtual void openBox ()
a slot to open a widget upon button press event
Private Member Functions
void createButtonBox (QString _buttonName=`Select &Colour`)
function to create the button box for the pop up
Private Attributes
QString m_buttonName
string to hold button's name
GLenum m_buttonType
enum for the button type, used for defining type
unsigned int m_id
id to access specific buttons and shader locations
QDialogButtonBox * m_buttonBox
button box used to activate the opening of the widget
QGridLayout * m_gridLayout
layout for the button box to be stored within
Detailed Description
Parent class of different button types to set uniform values.
Definition at line 47 of file Button.h.
Constructor & Destructor Documentation
Button::Button (QWidget * parent = 0)
default constructor to create the button
Parameters
in the parent window is defaulted to nothing
Definition at line 13 of file Button.cpp.
References createButtonBox().
                              : QDialog(parent)
{
  createButtonBox();
}
Button::Button (QString _buttonName, GLenum _buttonType, QLayout * _layout, GLuint _id, ButtonLib * _libParent, NGLScene * _sceneParent, QWidget * parent = 0)
constructor to create the button, custom variables can also be assigned
Parameters
in name of the button to be used
in the layout environment for the button to be attached to
in the id used to access the button information
in the parent window is defaulted to nothing
Definition at line 18 of file Button.cpp.
References createButtonBox(), m_button, m_buttonName, m_buttonType, m_id, m_libParent, m_parent, and m_sceneParent.
                                                                                                           
                                               : QDialog(parent)
{
  m_buttonName = _buttonName;
  m_buttonType = _buttonType;
  m_id=_id;
  createButtonBox(_buttonName);
  m_libParent=_libParent;
  m_sceneParent=_sceneParent;
  m_parent=parent;
  _layout->addWidget(m_button);
}
Member Function Documentation
void Button::createButtonBox (QString _buttonName = `Select &Colour`) [private]
function to create the button box for the pop up
Parameters
in button name
Definition at line 30 of file Button.cpp.
References m_button, and openBox().
{
  m_button = new QPushButton();
  m_button->setText(_buttonName);
  connect(m_button, SIGNAL(clicked()), this, SLOT(openBox()));
}
virtual ngl::Vec4 Button::getColour () [inline], [virtual]
returns the colour, stored by the button
Returns
m_colour
Reimplemented in ColourButton .
Definition at line 121 of file Button.h.
{return ngl::Vec4();}
virtual QColor Button::getColourQ () [inline], [virtual]
returns the QColour, stored by the button
Returns
m_colour
Reimplemented in ColourButton .
Definition at line 125 of file Button.h.
{return QColor();}
GLuint Button::getID () [inline]
returns the button ID, this will change based on shader location
Returns
m_id
Definition at line 106 of file Button.h.
References m_id.
{return m_id;}
QString Button::getName () [inline]
returns the current button name
Returns
m_buttonName
Definition at line 91 of file Button.h.
References m_buttonName.
{return m_buttonName;}
GLenum Button::getTypeEnum () [inline]
returns the current button type
Returns
m_buttonType
Definition at line 96 of file Button.h.
References m_buttonType.
{return m_buttonType;}
virtual float Button::getValue () [inline], [virtual]
returns the value, stored by the button
Returns
m_value
Reimplemented in FloatButton .
Definition at line 135 of file Button.h.
{return float();}
virtual ngl::Vec4 Button::getVec () [inline], [virtual]
returns the Vec4 held by the vector button class
Returns
m_value
Reimplemented in VecButton .
Definition at line 144 of file Button.h.
{return ngl::Vec4();}
virtual void Button::openBox () [inline], [private], [virtual], [slot]
a slot to open a widget upon button press event
Definition at line 183 of file Button.h.
{return;}
void Button::printValues () [virtual]
prints the button attribute values
Definition at line 37 of file Button.cpp.
References m_buttonName, and m_id.
{
  qDebug()<<"Name:"<<m_buttonName<<"\nID: "<<m_id;
}
virtual void Button::setColour (ngl::Vec4 _col) [inline], [virtual]
sets the colour to be used by colour buttons
Parameters
in the colour to be set within the colourButton class
Reimplemented in ColourButton .
Definition at line 111 of file Button.h.
{return;}
virtual void Button::setColour (QColor _col) [inline], [virtual]
overloaded function to set the colour
Parameters
in the colour to be set within the colourButton class
Reimplemented in ColourButton .
Definition at line 116 of file Button.h.
{return;}
void Button::setID (unsigned int _id) [inline]
sets the current ID for the button, from its' shader location
Parameters
in the location ID for the button id
Definition at line 101 of file Button.h.
References m_id.
{m_id=_id;}
virtual void Button::setValue (float _val) [inline], [virtual]
sets the value to be for float attributes
Parameters
in the value to be set within the floatButton class
Reimplemented in FloatButton .
Definition at line 130 of file Button.h.
{return;}
virtual void Button::setVec (ngl::Vec4 _value) [inline], [virtual]
sets the vector value for Vec3s or positions
Parameters
in _value to be set within the VecButton class
Reimplemented in VecButton .
Definition at line 149 of file Button.h.
{return;}
Member Data Documentation
QPushButton* Button::m_button
button object to be pressed by user to open relevant widget
Definition at line 67 of file Button.h.
QDialogButtonBox* Button::m_buttonBox [private]
button box used to activate the opening of the widget
Definition at line 167 of file Button.h.
QString Button::m_buttonName [private]
string to hold button's name
Definition at line 155 of file Button.h.
GLenum Button::m_buttonType [private]
enum for the button type, used for defining type
Definition at line 159 of file Button.h.
QGridLayout* Button::m_gridLayout [private]
layout for the button box to be stored within
Definition at line 171 of file Button.h.
unsigned int Button::m_id [private]
id to access specific buttons and shader locations
Definition at line 163 of file Button.h.
ButtonLib* Button::m_libParent
pointer to the button library parent
Definition at line 55 of file Button.h.
QWidget* Button::m_parent
pointer to the parent window to know where to attach to
Definition at line 63 of file Button.h.
NGLScene* Button::m_sceneParent
pointer to the scene so that update can be called
Definition at line 59 of file Button.h.
The documentation for this class was generated from the following files:
Button.h
Button.cpp