ButtonLib Class Reference
Stores vector of buttons with values and updates uniforms.
#include <ButtonLib.h>
Public Member Functions
ButtonLib (ParserLib *_parser, QLayout *_layout, NGLScene *_scene, QWidget *_parent=0)
constructor to create the button library
void createButtons ()
call to a function to create the buttons in the gui
void updateButtons ()
call to update the buttons
void printUniforms ()
prints the uniforms for debugging purposes
void updateShaderValues ()
sets the shader values from the button values
Private Attributes
QLayout * m_layout
gui layout for the buttons to be stored in
QWidget * m_parent
gui parent for the layout
ParserLib * m_parser
pointer to the parser to access and set uniform values
NGLScene * m_scene
pointer to the NGLScene, gl Widget
std::vector< Button * > m_buttonList
vector of buttons to dynamically and delete different types
Detailed Description
Stores vector of buttons with values and updates uniforms.
Definition at line 25 of file ButtonLib.h.
Constructor & Destructor Documentation
ButtonLib::ButtonLib (ParserLib * _parser, QLayout * _layout, NGLScene * _scene, QWidget * _parent = 0)
constructor to create the button library
Parameters
in _parser the parser to check and set uniforms
in _layout the layout environment for the buttons to be attached to
in _scene the NGLScene for the GUI
in _parent the parent window for the buttons
Definition at line 3 of file ButtonLib.cpp.
References createButtons(), m_layout, m_parent, m_parser, m_scene, and updateShaderValues().
{
  m_parser=_parser;
  m_layout=_layout;
  m_parent=_parent;
  m_scene=_scene;
  createButtons();
  updateShaderValues();
}
Member Function Documentation
void ButtonLib::createButtons ()
call to a function to create the buttons in the gui
Definition at line 13 of file ButtonLib.cpp.
References m_buttonList, m_layout, m_parent, m_parser, m_scene, ParserLib::m_uniformList, ColourButton::setColour(), VecButton::setUpButton(), and FloatButton::setValue().
{
  for(auto uniform : m_parser->m_uniformList)
  {
    QString _uniformName = QString::fromStdString(uniform->getName());
    GLenum _uniformType = uniform->getTypeEnum();
    if(_uniformType==GL_FLOAT_VEC4)
    {
      ngl::Vec4 _uniformVec=uniform->getVec4();
      ColourButton *tempButton = new ColourButton(_uniformName,
                                                  _uniformType,
                                                  m_layout,
                                                  uniform->getLocation(),
                                                  this,
                                                  m_scene,
                                                  m_parent);
      tempButton->setColour(_uniformVec);
      m_buttonList.push_back(tempButton);
    }
    if(_uniformType==GL_FLOAT)
    {
      float _uniformFloat=uniform->getFloat();
      FloatButton *tempButton = new FloatButton(_uniformName,
                                                _uniformType,
                                                m_layout,
                                                uniform->getLocation(),
                                                this,
                                                m_scene,
                                                m_parent);
      tempButton->setValue(_uniformFloat);
      m_buttonList.push_back(tempButton);
    }
    if(_uniformType==GL_FLOAT_VEC3)
    {
      ngl::Vec3 _uniformVec=uniform->getVec3();
      VecButton *tempButton = new VecButton(_uniformName,
                                                  _uniformType,
                                                  m_layout,
                                                  uniform->getLocation(),
                                                  this,
                                                  m_scene,
                                                  m_parent);
      tempButton->setUpButton(_uniformVec);
      m_buttonList.push_back(tempButton);
    }
  }
}
void ButtonLib::printUniforms ()
prints the uniforms for debugging purposes
void ButtonLib::updateButtons ()
call to update the buttons
Definition at line 61 of file ButtonLib.cpp.
References createButtons(), and m_buttonList.
{
  if(m_buttonList.size()==0)
  {
    createButtons();
  }
  else
  {
    std::vector<Button*> _buttonDup = m_buttonList;
    for(auto uniform : m_buttonList)
    {
      delete uniform->m_button;
    }
    m_buttonList.resize(0);
    createButtons();
    for(auto uniform: m_buttonList)
    {
      for(uint i=0; i<_buttonDup.size(); ++i)
      {
        if(uniform->getName()==_buttonDup[i]->getName() && uniform->getTypeEnum()==_buttonDup[i]->
      getTypeEnum())
        {
          if(uniform->getTypeEnum()==GL_FLOAT_VEC4)
          {
            uniform->setColour(_buttonDup[i]->getColourQ());
          }
          if(uniform->getTypeEnum()==GL_FLOAT)
          {
            uniform->setValue(_buttonDup[i]->getValue());
          }
          if(uniform->getTypeEnum()==GL_FLOAT_VEC3)
          {
            uniform->setVec(_buttonDup[i]->getVec());
          }
        }
      }
    }
  }
}
void ButtonLib::updateShaderValues ()
sets the shader values from the button values
Definition at line 99 of file ButtonLib.cpp.
References m_buttonList, m_parser, and ParserLib::m_uniformList.
{
  for(auto uniform: m_parser->m_uniformList)
  {
    if(uniform->getTypeEnum()==GL_FLOAT_VEC4)
    {
      for(auto button: m_buttonList)
      {
        if(uniform->getLocation()==button->getID())
        {
          ngl::Vec4 temp = button->getColour();
          uniform->setVec4(temp);
          break;
        }
      }
    }
    if(uniform->getTypeEnum()==GL_FLOAT)
    {
      for(auto button: m_buttonList)
      {
        if(uniform->getLocation()==button->getID())
        {
          float temp = button->getValue();
          uniform->setFloat(temp);
          break;
        }
      }
    }
    if(uniform->getTypeEnum()==GL_FLOAT_VEC3)
    {
      for(auto button: m_buttonList)
      {
        if(uniform->getLocation()==button->getID())
        {
          ngl::Vec4 temp = button->getVec();
          uniform->setVec3(ngl::Vec3(temp.m_x,
                                     temp.m_y,
                                     temp.m_z));
          ngl::Vec3 newV = uniform->getVec3();
          break;
        }
      }
    }
  }
}
Member Data Documentation
std::vector<Button*> ButtonLib::m_buttonList [private]
vector of buttons to dynamically and delete different types
Definition at line 74 of file ButtonLib.h.
QLayout* ButtonLib::m_layout [private]
gui layout for the buttons to be stored in
Definition at line 58 of file ButtonLib.h.
QWidget* ButtonLib::m_parent [private]
gui parent for the layout
Definition at line 62 of file ButtonLib.h.
ParserLib* ButtonLib::m_parser [private]
pointer to the parser to access and set uniform values
Definition at line 66 of file ButtonLib.h.
NGLScene* ButtonLib::m_scene [private]
pointer to the NGLScene, gl Widget
Definition at line 70 of file ButtonLib.h.
The documentation for this class was generated from the following files:
ButtonLib.h
ButtonLib.cpp