NewProjectWizard Class Reference
The main Wizard that contains all the pages for the new project.
#include <NewProjectWizard.h>
Public Member Functions
NewProjectWizard (QWidget *parent=0)
Constructor, passing a child of parent.
void accept () Q_DECL_OVERRIDE
This is run when the dialog has been accepted.
const OutputData * getOutput () const
Gets the output of the wizard when it has been completed.
Public Attributes
QItemSelectionModel * m_vertexSelectModel
The vertex selection model for the vertex treeview.
QItemSelectionModel * m_fragmentSelectModel
The fragment selection model for the fragment treeview.
QFileSystemModel * m_fileModel
The file model used for both of the vertex and fragment treeviews.
Private Attributes
OutputData * m_output
The output data stored on completion of the wizard.
Detailed Description
The main Wizard that contains all the pages for the new project.
Definition at line 58 of file NewProjectWizard.h.
Constructor & Destructor Documentation
NewProjectWizard::NewProjectWizard (QWidget * parent = 0)
Constructor, passing a child of parent.
Parameters
in parent The parent for which this will be the child of.
Definition at line 31 of file NewProjectWizard.cpp.
References m_fileModel, and m_output.
                                                 : QWizard(parent)
{
  // Setup file model
  m_fileModel = new QFileSystemModel;
  m_fileModel->setRootPath(QDir::currentPath() + "/shaders/files");
  m_fileModel->removeColumns(1,3);
  // Create the structr for storing output data
  m_output = new OutputData;
  // Add the pages to the wizard
  addPage(new IntroPage(this));
  addPage(new ProjectInfoPage(this));
  addPage(new GlslFilesPage(this));
  addPage(new GlslOrderPage(this));
  addPage(new ConclusionPage(this));
  setWindowTitle(tr("New Project Wizard"));
}
Member Function Documentation
void NewProjectWizard::accept ()
This is run when the dialog has been accepted.
Definition at line 52 of file NewProjectWizard.cpp.
References GlslOrderPage::getFragListWidget(), GlslOrderPage::getVertListWidget(), m_fileModel, m_fragmentSelectModel, OutputData::m_fragSource, m_output, OutputData::m_projectDir, OutputData::m_projectName, m_vertexSelectModel, OutputData::m_vertSource, and CEBRaise::QtFileError().
{
  // get project name and directory
  m_output->m_projectName = field("projectName").toString().toStdString();
  m_output->m_projectDir = field("projectDirectory").toString().toStdString();
  // create glsl version string
  QString ver = QString("#version %1 %2\n\n")
                .arg(field("glslVersion").toString(),
                     field("glslProfile").toString());
  // get the selected rows from the vertex and fragment selection models used
  // with the treeviews
  QModelIndexList vertFiles = m_vertexSelectModel->selectedRows();
  QModelIndexList fragFiles = m_fragmentSelectModel->selectedRows();
  // Get the glsl order page
  GlslOrderPage* glslOrderPg = static_cast<GlslOrderPage*>(page(3));
  // Setup variables for getting the correct order of the files
  // ordered filenames (from the qlistwidgets)
  QStringList vertexOrderFileNames, fragmentOrderFileNames;
  // unordered filenames (from the qtreeviews)
  QStringList vertFileNames, fragFileNames;
  // get the list of ordered files from the list widgets
  const QListWidget* vertFilesOrder = glslOrderPg->getVertListWidget();
  const QListWidget* fragFilesOrder = glslOrderPg->getFragListWidget();
  // create the unordered and ordered file name lists for vertex
  for (int i=0; i<vertFilesOrder->count(); ++i)
  {
    vertFileNames.append(m_fileModel->fileInfo(vertFiles.at(i)).fileName());
    vertexOrderFileNames.append(vertFilesOrder->item(i)->text());
  }
  // create the unordered and ordered file name lists for fragment
  for (int i=0; i<fragFilesOrder->count(); ++i)
  {
    fragFileNames.append(m_fileModel->fileInfo(fragFiles.at(i)).fileName());
    fragmentOrderFileNames.append(fragFilesOrder->item(i)->text());
  }
  // the final vertex and fragment strings
  QString vertexFilesString, fragmentFilesString;
  // Now find the correct index from the ordered list using the ordered and
  // un-ordered file name lists and get the file value from the file model
  for (int i=0; i<vertFileNames.length(); ++i)
  {
    // getting the correct index from the ordered file list
    int index = vertFileNames.indexOf(vertexOrderFileNames[i]);
    // get the file at the correct index from the selected rows in the QTreeView
    QFile vFile(m_fileModel->fileInfo(vertFiles.at(index)).absoluteFilePath());
    // open the file
    if (!vFile.open(QIODevice::ReadOnly | QIODevice::Text))
    {
      // Raise an error if failed
      CEBRaise::QtFileError(vFile.error(),
                            m_fileModel->fileInfo(vertFiles.at(index))
                                                           .absoluteFilePath());
    }
    // append the file to a single string
    QTextStream in(&vFile);
    vertexFilesString.append(in.readAll());
    vertexFilesString.append("\n");
  }
  // REPEAT above again
  // Now find the correct index from the ordered list using the ordered and
  // un-ordered file name lists and get the file value from the file model
  for (int i=0; i<fragFileNames.length(); ++i)
  {
    // getting the correct index from the ordered file list
    int index = fragFileNames.indexOf(fragmentOrderFileNames[i]);
    // get the file at the correct index from the selected rows in the QTreeView
    QFile fFile(m_fileModel->fileInfo(fragFiles.at(index)).absoluteFilePath());
    // open the file
    if (!fFile.open(QIODevice::ReadOnly | QIODevice::Text))
    {
      // Raise an error if failed
      CEBRaise::QtFileError(fFile.error(),
                            m_fileModel->fileInfo(fragFiles.at(index))
                                                           .absoluteFilePath());
    }
    // append the file to a single string
    QTextStream in(&fFile);
    fragmentFilesString.append(in.readAll());
    fragmentFilesString.append("\n");
  }
  // check if each of the file strings already contains a version. If it doesn't
  // then push to front
  if(!vertexFilesString.contains("#version"))
  {
    vertexFilesString.push_front(ver+"\n");
  }
  // same as above
  if(!fragmentFilesString.contains("#version"))
  {
    fragmentFilesString.push_front(ver+"\n");
  }
  // store in output
  m_output->m_vertSource = vertexFilesString;
  m_output->m_fragSource = fragmentFilesString;
  // accept the dialog
  QDialog::accept();
}
const OutputData* NewProjectWizard::getOutput () const [inline]
Gets the output of the wizard when it has been completed.
Returns
the output
Definition at line 90 of file NewProjectWizard.h.
References m_output.
{return m_output;}
Member Data Documentation
QFileSystemModel* NewProjectWizard::m_fileModel
The file model used for both of the vertex and fragment treeviews.
Definition at line 75 of file NewProjectWizard.h.
QItemSelectionModel* NewProjectWizard::m_fragmentSelectModel
The fragment selection model for the fragment treeview.
Definition at line 71 of file NewProjectWizard.h.
OutputData* NewProjectWizard::m_output [private]
The output data stored on completion of the wizard.
Definition at line 97 of file NewProjectWizard.h.
QItemSelectionModel* NewProjectWizard::m_vertexSelectModel
The vertex selection model for the vertex treeview.
Definition at line 67 of file NewProjectWizard.h.
The documentation for this class was generated from the following files:
NewProjectWizard.h
NewProjectWizard.cpp