GlslFilesPage Class Reference
The project wizard page for selecting glsl files in.
#include <NewProjectWizard.h>
Public Member Functions
GlslFilesPage (QWidget *parent=0)
Constructor, passing a child of parent.
Protected Member Functions
void initializePage () Q_DECL_OVERRIDE
Used to prepare the Wizard page before it is shown and set default values.
Private Slots
void vertexSelectChanged (const QItemSelection &_selected, const QItemSelection &_deselected)
Activated when an object in the Vertex Treeview is changed.
void fragmentSelectChanged (const QItemSelection &_selected, const QItemSelection &_deselected)
Activated when an object in the Fragment Treeview is changed.
Private Member Functions
void deselectDir (const QItemSelection &_selected, QItemSelectionModel *_selectModel)
Deselects selected directories so only files can be selected in the treeviews.
Private Attributes
NewProjectWizard * m_wizard
The new project wizard that this page is a part of (the parent)
QGroupBox * m_gb_glslFiles
Group box for the glsl files.
QLabel * m_l_fragmentName
Label for the fragment name.
QLabel * m_l_vertexName
Label for the vertex name.
QLineEdit * m_le_fragmentName
Line edit for the fragment name.
QLineEdit * m_le_vertexName
Line edit for the vertex name.
QLabel * m_l_fragmentSelectFiles
Label for the fragment select files.
QLabel * m_l_vertexSelectFiles
Label fro the vertex select files.
QTreeView * m_tv_fragmentSelectFiles
Treeview for selecting fragment files.
QTreeView * m_tv_vertexSelectFiles
Treeview for selecting vertex files.
Detailed Description
The project wizard page for selecting glsl files in.
Todo
Todo Make an inherited QWizardPage class that takes the parent (being qWizard) and storing it as a member. Currenlty just repeating this for GlslFilesPage and GlslOrderPage
Definition at line 207 of file NewProjectWizard.h.
Constructor & Destructor Documentation
GlslFilesPage::GlslFilesPage (QWidget * parent = 0)
Constructor, passing a child of parent.
Parameters
in parent The parent for which this will be the child of.
Todo
Todo Make the two tree views into a single function since a lot of values are set the same. Just done this for the time being for speed.
Definition at line 277 of file NewProjectWizard.cpp.
References fragmentSelectChanged(), NewProjectWizard::m_fileModel, NewProjectWizard::m_fragmentSelectModel, m_gb_glslFiles, m_l_fragmentName, m_l_fragmentSelectFiles, m_l_vertexName, m_l_vertexSelectFiles, m_le_fragmentName, m_le_vertexName, m_tv_fragmentSelectFiles, m_tv_vertexSelectFiles, NewProjectWizard::m_vertexSelectModel, m_wizard, and vertexSelectChanged().
  : QWizardPage(parent)
{
  m_wizard = static_cast<NewProjectWizard*>(parent);
  QString shadersPath = QDir::currentPath() + "/shaders/files";
  setTitle(tr("Shaders & GLSL Files"));
  setSubTitle(tr("Specify the name of the Vertex and Fragment shaders as well "
                 "what GLSL files will be linked."));
  m_l_vertexName = new QLabel(tr("Vertex Name:"));
  m_le_vertexName = new QLineEdit();
  m_l_vertexName->setBuddy(m_le_vertexName);
  m_l_fragmentName = new QLabel(tr("Fragment Name:"));
  m_le_fragmentName = new QLineEdit();
  m_l_fragmentName->setBuddy(m_le_fragmentName);
  m_l_vertexSelectFiles = new QLabel(tr("Vertex Files:"));
  m_l_fragmentSelectFiles = new QLabel(tr("Fragment Files:"));
  m_tv_vertexSelectFiles = new QTreeView;
  m_tv_fragmentSelectFiles = new QTreeView;
  std::vector<QTreeView*> tViews = {m_tv_vertexSelectFiles,
                                    m_tv_fragmentSelectFiles};
  for (auto tv: tViews)
  {
    tv->setModel(m_wizard->m_fileModel);
    // set directory to show
    tv->setRootIndex(m_wizard->m_fileModel->index(shadersPath));
    tv->setSelectionMode(QAbstractItemView::MultiSelection);
    // show only file name
    tv->setColumnHidden(1,true);
    tv->setColumnHidden(2,true);
    tv->setColumnHidden(3,true);
  }
  // store the selection models
  m_wizard->m_vertexSelectModel = m_tv_vertexSelectFiles->selectionModel();
  m_wizard->m_fragmentSelectModel = m_tv_fragmentSelectFiles->selectionModel();
  // setup selection connections for de-selecting folders
  connect(m_wizard->m_vertexSelectModel,
          SIGNAL(selectionChanged(const QItemSelection&,
                                  const QItemSelection&)),
          this,
          SLOT(vertexSelectChanged(const QItemSelection&,
                                   const QItemSelection&)));
  connect(m_wizard->m_fragmentSelectModel,
          SIGNAL(selectionChanged(const QItemSelection&,
                                  const QItemSelection&)),
          this,
          SLOT(fragmentSelectChanged(const QItemSelection&,
                                     const QItemSelection&)));
  // register fileds for wizard
  registerField("vertexFileName*", m_le_vertexName);
  registerField("fragmentFileName*", m_le_fragmentName);
  //layouts
  m_gb_glslFiles = new QGroupBox(tr("Select GLSL Files"));
  m_gb_glslFiles->setMinimumHeight(300);
  QGridLayout *groupBoxLayout = new QGridLayout;
  groupBoxLayout->addWidget(m_l_vertexSelectFiles, 0, 0);
  groupBoxLayout->addWidget(m_l_fragmentSelectFiles, 0, 1);
  groupBoxLayout->addWidget(m_tv_vertexSelectFiles, 1, 0);
  groupBoxLayout->addWidget(m_tv_fragmentSelectFiles, 1, 1);
  m_gb_glslFiles->setLayout(groupBoxLayout);
  QGridLayout *layout = new QGridLayout;
  layout->addWidget(m_l_vertexName, 0, 0);
  layout->addWidget(m_le_vertexName, 0, 1);
  layout->addWidget(m_l_fragmentName, 1, 0);
  layout->addWidget(m_le_fragmentName, 1, 1);
  layout->addWidget(m_gb_glslFiles, 2, 0, 1, 2);
  setLayout(layout);
}
Member Function Documentation
void GlslFilesPage::deselectDir (const QItemSelection & _selected, QItemSelectionModel * _selectModel) [private]
Deselects selected directories so only files can be selected in the treeviews.
Parameters
in _selected The items selected in the treeview
in _selectModel The selection model used with the selections treeview
Definition at line 382 of file NewProjectWizard.cpp.
References NewProjectWizard::m_fileModel, and m_wizard.
{
  QModelIndexList items = _selected.indexes();
  for (auto index: items)
  {
    // check if the selected item is a folder, if it is deselect it
    // we only want files
    QFileInfo info = m_wizard->m_fileModel->fileInfo(index);
    if (info.isDir())
    {
      _selectModel->select(index, QItemSelectionModel::Deselect);
    }
  }
}
void GlslFilesPage::fragmentSelectChanged (const QItemSelection & _selected, const QItemSelection & _deselected) [private], [slot]
Activated when an object in the Fragment Treeview is changed.
Parameters
in _selected the objects that have been selected in the treeview
in _deselected the objects that have been deselected in the treeview
Definition at line 375 of file NewProjectWizard.cpp.
References deselectDir(), NewProjectWizard::m_fragmentSelectModel, and m_wizard.
{
  deselectDir(_selected, m_wizard->m_fragmentSelectModel);
}
void GlslFilesPage::initializePage () [protected]
Used to prepare the Wizard page before it is shown and set default values.
Definition at line 360 of file NewProjectWizard.cpp.
References m_le_fragmentName, and m_le_vertexName.
{
  QString projectName = field("projectName").toString();
  m_le_vertexName->setText(projectName + "Vertex");
  m_le_fragmentName->setText(projectName + "Fragment");
}
void GlslFilesPage::vertexSelectChanged (const QItemSelection & _selected, const QItemSelection & _deselected) [private], [slot]
Activated when an object in the Vertex Treeview is changed.
Parameters
in _selected the objects that have been selected in the treeview
in _deselected the objects that have been deselected in the treeview
Definition at line 368 of file NewProjectWizard.cpp.
References deselectDir(), NewProjectWizard::m_vertexSelectModel, and m_wizard.
{
  deselectDir(_selected, m_wizard->m_vertexSelectModel);
}
Member Data Documentation
QGroupBox* GlslFilesPage::m_gb_glslFiles [private]
Group box for the glsl files.
Definition at line 228 of file NewProjectWizard.h.
QLabel* GlslFilesPage::m_l_fragmentName [private]
Label for the fragment name.
Definition at line 232 of file NewProjectWizard.h.
QLabel* GlslFilesPage::m_l_fragmentSelectFiles [private]
Label for the fragment select files.
Definition at line 248 of file NewProjectWizard.h.
QLabel* GlslFilesPage::m_l_vertexName [private]
Label for the vertex name.
Definition at line 236 of file NewProjectWizard.h.
QLabel* GlslFilesPage::m_l_vertexSelectFiles [private]
Label fro the vertex select files.
Definition at line 252 of file NewProjectWizard.h.
QLineEdit* GlslFilesPage::m_le_fragmentName [private]
Line edit for the fragment name.
Definition at line 240 of file NewProjectWizard.h.
QLineEdit* GlslFilesPage::m_le_vertexName [private]
Line edit for the vertex name.
Definition at line 244 of file NewProjectWizard.h.
QTreeView* GlslFilesPage::m_tv_fragmentSelectFiles [private]
Treeview for selecting fragment files.
Definition at line 256 of file NewProjectWizard.h.
QTreeView* GlslFilesPage::m_tv_vertexSelectFiles [private]
Treeview for selecting vertex files.
Definition at line 260 of file NewProjectWizard.h.
NewProjectWizard* GlslFilesPage::m_wizard [private]
The new project wizard that this page is a part of (the parent)
Definition at line 224 of file NewProjectWizard.h.
The documentation for this class was generated from the following files:
NewProjectWizard.h
NewProjectWizard.cpp