ShaderManager Class Reference
Handles creation and compilation of shaders via modified NGL ShaderLib.
#include <ShaderManager.h>
Public Member Functions
ShaderManager ()
default constructor for ShaderManager class
void createShaderProgram (std::string _name)
method to create a new shader program object
void use (uint _shaderType)
method to set OpenGL to use the current shader program
void initialize ()
method called when 1st opening program to initialise the default phong shader
void compileShader (QString _vertSource, QString _fragSource)
method called to compile the currently active shader
bool isInit ()
method to return whether the shader manager successfully initialised
bool compileStatus ()
method to return whether the current shader successfully compiled
QString getErrorLog ()
method to return the most recent error log
void setData (std::string _name, std::string _vert, std::string _frag)
method to set the data for the current shader
ShaderProgramData getData ()
get the current data from the shader manager
Private Member Functions
bool checkCompileError (std::string _shaderName, QString *o_log)
method to check compiling errors for a single shader object
bool checkAllCompileError (QString *o_log)
method to check compiling errors for all shader objects attached
bool checkLinkError (QString *o_log)
method to check link error
Private Attributes
bool m_init
flag for success of shader manager initialisation
bool m_compileStatus
flag for the success of compilation of currently active shader
QString m_errorLog
error log for storing compiling errors
ShaderProgramData m_data
structure containing names for currently actuve shader program
GLuint m_textureName
variable holding the identity of the bound texture map
Detailed Description
Handles creation and compilation of shaders via modified NGL ShaderLib.
will check and return compile status to user whether successful or unsuccessful.
Definition at line 34 of file ShaderManager.h.
Constructor & Destructor Documentation
ShaderManager::ShaderManager ()
default constructor for ShaderManager class
Definition at line 10 of file ShaderManager.cpp.
References m_data, ShaderProgramData::m_frag, m_init, ShaderProgramData::m_name, and ShaderProgramData::m_vert.
{
  m_data.m_name = "untitled";
  m_data.m_vert = "";
  m_data.m_frag = "";
  m_init = false;
}
Member Function Documentation
bool ShaderManager::checkAllCompileError (QString * o_log) [private]
method to check compiling errors for all shader objects attached
to currently active shader program
Parameters
o_log the output error log
Definition at line 254 of file ShaderManager.cpp.
References checkCompileError(), m_data, ShaderProgramData::m_frag, and ShaderProgramData::m_vert.
{
  GLint isAllCompiled = GL_TRUE;
  QString temp_log;
  std::vector <std::string> shaderPrograms = {m_data.m_vert, m_data.m_frag};
  // Iterate between vertex and fragment shaders to check compile errors
  for (auto shaderProg: shaderPrograms)
  {
    GLint isCompiled = checkCompileError(shaderProg, &temp_log);
    if (!isCompiled)
    {
      o_log->append(QString("%1:\n").arg(shaderProg.c_str()));
      o_log->append(temp_log);
    }
    if (isCompiled == GL_FALSE)
      isAllCompiled = isCompiled;
  }
  return isAllCompiled;
}
bool ShaderManager::checkCompileError (std::string _shaderName, QString * o_log) [private]
method to check compiling errors for a single shader object
Parameters
_shadeName the name of the shader object to check
o_log the output error log
Definition at line 195 of file ShaderManager.cpp.
{
  GLint isCompiled = GL_FALSE;
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  GLuint shaderId = shader->getShaderID(_shaderName);
  // Get compile status of shader
  glGetShaderiv(shaderId, GL_COMPILE_STATUS, &isCompiled);
  if(isCompiled == GL_FALSE)
  {
    // Receive info log
    GLint maxLength = 0;
    glGetShaderiv(shaderId, GL_INFO_LOG_LENGTH, &maxLength);
    // The maxLength includes the NULL character
    std::vector<GLchar> errorLog(maxLength);
    glGetShaderInfoLog(shaderId, maxLength, &maxLength, &errorLog[0]);
    // Write error log to an std::string to be output at QString
    std::string s(errorLog.begin(), errorLog.end());
    QString errLog = QString(s.c_str());
    *o_log = errLog;
  }
  return isCompiled;
}
bool ShaderManager::checkLinkError (QString * o_log) [private]
method to check link error
Parameters
o_log the output error log
Definition at line 223 of file ShaderManager.cpp.
References m_data, and ShaderProgramData::m_name.
{
  GLint isCompiled = GL_FALSE;
  ngl::ShaderLib *shader=ngl::ShaderLib::instance();
  GLuint progId = shader->getProgramID(m_data.m_name);
  GLint infologLength = 0;
  glGetProgramiv(progId,GL_INFO_LOG_LENGTH,&infologLength);
  if(infologLength > 0)
  {
    GLint charsWritten = 0;
    std::vector<GLchar> errorLog(infologLength);
    glGetProgramInfoLog(progId, infologLength, &charsWritten, &errorLog[0]);
    // Write error log to an std::string to be output at QString
    std::string s(errorLog.begin(), errorLog.end());
    QString errLog = QString(s.c_str());
    glGetProgramiv(progId, GL_LINK_STATUS, &isCompiled);
    o_log->append(errLog);
    if(infologLength == GL_FALSE)
    {
      std::cerr<<"Program link failed \n";
    }
  }
  return isCompiled;
}
void ShaderManager::compileShader (QString _vertSource, QString _fragSource)
method called to compile the currently active shader
Parameters
_vertSource the source code for the vertex shader
_fragSource the source code for the fragment shader
Definition at line 143 of file ShaderManager.cpp.
References checkAllCompileError(), checkLinkError(), m_compileStatus, m_data, m_errorLog, ShaderProgramData::m_frag, ShaderProgramData::m_name, m_textureName, and ShaderProgramData::m_vert.
{
  //clear the error log
  m_errorLog.clear();
  //grab an instance of the shader lib
  ngl::ShaderLib *shaderLib=ngl::ShaderLib::instance();
  // convert from QString to std::string for compiling
  shaderLib->loadShaderSourceFromString(m_data.m_vert, _vertSource.toStdString());
  shaderLib->loadShaderSourceFromString(m_data.m_frag, _fragSource.toStdString());
  // compile shaders
  shaderLib->compileShader(m_data.m_vert);
  shaderLib->compileShader(m_data.m_frag);
  //check for compile errors
  if (!checkAllCompileError(&m_errorLog))
  {
    // output any compile errors to user
    std::cout << m_errorLog.toUtf8().constData();
    m_compileStatus = false;
  }
  else
  {
    m_compileStatus = true;
    // add them to the program
    shaderLib->attachShaderToProgram(m_data.m_name,m_data.m_vert);
    shaderLib->attachShaderToProgram(m_data.m_name,m_data.m_frag);
    // now we have associated this data we can link the shader
    shaderLib->linkProgramObject(m_data.m_name);
    // use the shader program
    (*shaderLib)[m_data.m_name]->use();
    if (!checkLinkError(&m_errorLog))
    {
      // output any compile errors to user
      std::cout << m_errorLog.toUtf8().constData();
      m_compileStatus = false;
    }
    else
    {
      m_errorLog.append("No Errors");
    }
    ngl::Texture texture("textures/rustTexture.jpg");
    m_textureName=texture.setTextureGL();
  }
}
bool ShaderManager::compileStatus () [inline]
method to return whether the current shader successfully compiled
Definition at line 68 of file ShaderManager.h.
References m_compileStatus.
{return m_compileStatus;}
void ShaderManager::createShaderProgram (std::string _name)
method to create a new shader program object
Parameters
_name the name of the shader program to create
Definition at line 20 of file ShaderManager.cpp.
References m_data, ShaderProgramData::m_frag, ShaderProgramData::m_name, ShaderProgramData::m_vert, setData(), and use().
{
  //set our data
  setData(_name, _name+"Vertex", _name+"Fragment");
  //grab an instance of the shader lib
  ngl::ShaderLib *shaderLib = ngl::ShaderLib::instance();
  //create an empty shader program
  shaderLib->createShaderProgram(_name);
  //create empty shader objects for vertex and fragment shaders
  shaderLib->attachShader(m_data.m_vert, ngl::ShaderType::VERTEX);
  shaderLib->attachShader(m_data.m_frag, ngl::ShaderType::FRAGMENT);
  //attach empty shader objects to the shader program
  shaderLib->attachShaderToProgram(m_data.m_name, m_data.m_vert);
  shaderLib->attachShaderToProgram(m_data.m_name, m_data.m_frag);
  shaderLib->bindAttribute(m_data.m_name,0,"inVert");
  // attribute 1 is the UV data u,v (if present)
  shaderLib->bindAttribute(m_data.m_name,1,"inUV");
  // attribute 2 are the normals x,y,z
  shaderLib->bindAttribute(m_data.m_name,2,"inNormal");
  use(0);
}
ShaderProgramData ShaderManager::getData () [inline]
get the current data from the shader manager
Returns
the shader data
Definition at line 87 of file ShaderManager.h.
References m_data.
{return m_data;}
QString ShaderManager::getErrorLog () [inline]
method to return the most recent error log
Definition at line 72 of file ShaderManager.h.
References m_errorLog.
{return m_errorLog;}
void ShaderManager::initialize ()
method called when 1st opening program to initialise the default phong shader
The following section is from :- Jon Macey (2016) AffineTransforms [online]. [Accessed 2016]. Available from: https://github.com/NCCA/AffineTransforms.
End of Citation
Definition at line 62 of file ShaderManager.cpp.
References checkAllCompileError(), m_compileStatus, m_data, m_errorLog, m_init, ShaderProgramData::m_name, and setData().
{
  //set our data
  setData("Phong", "PhongVertex", "PhongFragment");
  //grab an instance of shader manager
  ngl::ShaderLib *shaderLib=ngl::ShaderLib::instance();
  //create an empty shader program called Phong
  shaderLib->createShaderProgram("Phong");
  // create and empty shader objects from fragment and vertex shaders
  shaderLib->attachShader("PhongVertex",ngl::ShaderType::VERTEX);
  shaderLib->attachShader("PhongFragment",ngl::ShaderType::FRAGMENT);
  // load the source code to the shader objects
  shaderLib->loadShaderSource("PhongVertex","shaders/PhongVertex.glsl");
  shaderLib->loadShaderSource("PhongFragment","shaders/PhongFragment.glsl");
  // compile the shaders
  shaderLib->compileShader("PhongFragment");
  shaderLib->compileShader("PhongVertex");
  // check if the shader compiled successfully
  if (!checkAllCompileError(&m_errorLog))
  {
    // output code errors to user
    std::cout << m_errorLog.toUtf8().constData();
    m_compileStatus = false;
    std::cout<<"Initial Program compilation fail"<<std::endl;
  }
  else
  {
    // user's code has no errors, will now be attached to program
    m_compileStatus = true;
    shaderLib->attachShaderToProgram("Phong","PhongVertex");
    shaderLib->attachShaderToProgram("Phong","PhongFragment");
    // now bind the shader attributes for most NGL primitives we use the following
    // layout attribute 0 is the vertex data (x,y,z)
    shaderLib->bindAttribute("Phong",0,"inVert");
    // attribute 1 is the UV data u,v (if present)
    shaderLib->bindAttribute("Phong",1,"inUV");
    // attribute 2 are the normals x,y,z
    shaderLib->bindAttribute("Phong",2,"inNormal");
    // now we have associated this data we can link the shader
    shaderLib->linkProgramObject("Phong");
    // and make it active ready to load values
    shaderLib->use(m_data.m_name);
    shaderLib->createShaderProgram("normalShader");
    constexpr auto normalVert="normalVertex";
    constexpr auto normalGeo="normalGeo";
    constexpr auto normalFrag="normalFrag";
    shaderLib->attachShader(normalVert,ngl::ShaderType::VERTEX);
    shaderLib->attachShader(normalFrag,ngl::ShaderType::FRAGMENT);
    shaderLib->loadShaderSource(normalVert,"shaders/normalVertex.glsl");
    shaderLib->loadShaderSource(normalFrag,"shaders/normalFragment.glsl");
    shaderLib->compileShader(normalVert);
    shaderLib->compileShader(normalFrag);
    shaderLib->attachShaderToProgram("normalShader",normalVert);
    shaderLib->attachShaderToProgram("normalShader",normalFrag);
    shaderLib->attachShader(normalGeo,ngl::ShaderType::GEOMETRY);
    shaderLib->loadShaderSource(normalGeo,"shaders/normalGeo.glsl");
    shaderLib->compileShader(normalGeo);
    shaderLib->attachShaderToProgram("normalShader",normalGeo);
    shaderLib->linkProgramObject("normalShader");
    shaderLib->use("normalShader");
    // now pass the modelView and projection values to the shader
    shaderLib->setUniform("normalSize",0.1f);
    shaderLib->setUniform("vertNormalColour",1.0f,1.0f,0.0f,1.0f);
    shaderLib->setUniform("faceNormalColour",.0f,1.0f,0.0f,1.0f);
    shaderLib->setShaderParam1i("drawFaceNormals",true);
    shaderLib->setShaderParam1i("drawVertexNormals",true);
    // set initialise flag to true
    m_init = true;
  }
}
bool ShaderManager::isInit () [inline]
method to return whether the shader manager successfully initialised
Definition at line 64 of file ShaderManager.h.
References m_init.
{return m_init;}
void ShaderManager::setData (std::string _name, std::string _vert, std::string _frag) [inline]
method to set the data for the current shader
Parameters
_name the name of the the shader
_vert the name of the vertex shader object
_frag the name of the fragment shader object
Definition at line 79 of file ShaderManager.h.
References m_data, ShaderProgramData::m_frag, ShaderProgramData::m_name, and ShaderProgramData::m_vert.
    {m_data.m_name = _name;
     m_data.m_vert = _vert;
     m_data.m_frag = _frag;}
void ShaderManager::use (uint _shaderType)
method to set OpenGL to use the current shader program
Parameters
_shaderType int to switch to normals shader
Definition at line 46 of file ShaderManager.cpp.
References m_data, and ShaderProgramData::m_name.
{
  //grab an instance of shaderLib
  ngl::ShaderLib *shaderLib = ngl::ShaderLib::instance();
  enum shader{objectShader=0,objectNormals=1};
  //choose which shader to use
  switch(_shaderType)
  {
    case objectShader : { shaderLib->use(m_data.m_name); break; }
    case objectNormals: { (*shaderLib)["normalShader"]->use();break; }
    default: std::cerr<<"Invalid shaderType"<<std::endl; break;
  }
}
Member Data Documentation
bool ShaderManager::m_compileStatus [private]
flag for the success of compilation of currently active shader
Definition at line 97 of file ShaderManager.h.
ShaderProgramData ShaderManager::m_data [private]
structure containing names for currently actuve shader program
Definition at line 122 of file ShaderManager.h.
QString ShaderManager::m_errorLog [private]
error log for storing compiling errors
Definition at line 101 of file ShaderManager.h.
bool ShaderManager::m_init [private]
flag for success of shader manager initialisation
Definition at line 93 of file ShaderManager.h.
GLuint ShaderManager::m_textureName [private]
variable holding the identity of the bound texture map
Definition at line 126 of file ShaderManager.h.
The documentation for this class was generated from the following files:
ShaderManager.h
ShaderManager.cpp