NGLScene Class Reference
our main gl widget for NGL applications all drawing elements are put in this file
#include <NGLScene.h>
Public Slots
void initGL ()
the initialize class is called once when the window is created and we have a valid GL context use this to setup any default GL stuff
void setShapeType (int _type)
sets the shape type
void toggleWireframe (bool _state)
toggles the wireframe visibility
void toggleNormals (bool _state)
toggles the normals visibility
void toggleAxis (bool _state)
toggles the axis visibility
void toggleGrid (bool _state)
toggles the grid visibility
void setNormalSize (int _size)
sets the normal size
void exportUniform ()
exports the uniforms and writes them to the file ParsingOutput.txt
void resetObjPos ()
resets the position of the active OBJ in the OpenGL context
Signals
void createLineMarker (QString _shaderName, int _lineNum)
signal to create a line marker
void initializeGL ()
the signal for initialize GL
Public Member Functions
NGLScene (QWidget *_parent, ParserLib *_libParent, ShaderManager *_manager)
Constructor for GLWindow.
~NGLScene ()
dtor must close down ngl and release OpenGL resources
void paintGL ()
this is called everytime we want to draw the scene
void resizeGL (QResizeEvent *_event)
this is called everytime we resize the scene note: Qt 5.5.1 must have this implemented and uses it
void resizeGL (int _w, int _h)
this is called everytime we resize the scene note: Qt 5.x uses this instead! http://doc.qt.io/qt-5/qopenglwindow.html#resizeGL
void compileShader (QString _vertSource, QString _fragSource)
loads and compiles a shader from Qstrings passed from the text editor
void setMeshLocation (std::string _meshDirectory)
sets the file location you of a mesh
void setProject (std::string _name, QString _vertSource, QString _fragSource)
Creates a new project for the shader.
void importMeshName (const std::string &_name)
Changes the name of the m_mesh object directory.
void importTextureMap (const std::string &_name)
loads in a texture map and directly applies it to the OBJ. (Requires UVs)
Public Attributes
ParserLib * m_parser
the parser to deal with all the uniform values stored in the shader
Camera * m_camera
Pointer to inherit camera class. This is public for signal/slot access.
Private Member Functions
void mouseMoveEvent (QMouseEvent *_event)
this method is called every time a mouse is moved
void mousePressEvent (QMouseEvent *_event)
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
void mouseReleaseEvent (QMouseEvent *_event)
this method is called everytime the mouse button is released inherited from QObject and overridden here.
void loadMatricesToShader ()
method to load transform matrices to the shader
void wheelEvent (QWheelEvent *_event)
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
void keyPressEvent (QKeyEvent *_event)
this method should be called every time a keyboard button is pressed. Inherited from QObject and overridden here.
void objectTransform (uint _type)
Set object transformations depending on the shape type.
QString parseErrorLog (QString)
Stores a QString. Used to edit the error log message.
void drawAxis (ngl::Vec3 _pos)
Draw a xyz axis.
void drawObject (uint _type)
draw an object based on the m_shapeType; e.g. 0=mesh, 1=sphere, etc
void toggleObj ()
Activate the m_mesh .obj.
void createCamera ()
set the camera shape in the scene
Private Attributes
bool m_rotate
flag to indicate if the mouse button is pressed when dragging
int m_spinXFace
used to store the x rotation mouse value
int m_spinYFace
used to store the y rotation mouse value
int m_spinZFace
used to store the z rotation mouse value
ngl::Vec3 m_rotation
rotation of the teapot
bool m_translate
flag to indicate if the Right mouse button is pressed when dragging
int m_origX
the previous x mouse value
int m_origY
the previous y mouse value
int m_origXPos
the previous x mouse value for Position changes
int m_origYPos
the previous y mouse value for Position changes
ngl::Mat4 m_mouseGlobalTX
used to store the global mouse transforms
ngl::Camera m_cam
The camera.
ngl::Vec3 m_modelPos
the model position for mouse movement
ngl::Transformation m_transform
transformation stack for the gl transformations etc
bool m_wireframe
set the view to show wireframe
IO_XML * m_readFromXML
read from xml file
MainWindow * m_window
the main window that is the GUI
uint m_shapeType
defines the mesh type
bool m_toggleObj
A toggle used to import the .obj m_mesh.
bool m_toggleAxis
A toggle used to turn axis on and off.
bool m_drawNormals
A toggle used to draw normals.
bool m_drawGrid
A toggle used to draw a grid.
float m_normalSize
Stores the size of the normal.
GLuint m_textureName
stores the texture name
bool m_shaderError
If there is a shader error or not.
ShaderManager * m_shaderManager
Stores the shader manager which handles the setup and maintenance of shaders.
int m_cameraIndex
An index to access the cameras.
std::string m_meshLoc
A string to store the .obj m_mesh directory.
std::unique_ptr< ngl::Obj > m_mesh
Pointer to the VAO m_mesh.
Detailed Description
our main gl widget for NGL applications all drawing elements are put in this file
Definition at line 57 of file NGLScene.h.
Constructor & Destructor Documentation
NGLScene::NGLScene (QWidget * _parent, ParserLib * _libParent, ShaderManager * _manager)
Constructor for GLWindow.
Parameters
in _parent the parent window to create the GL context in
Definition at line 30 of file NGLScene.cpp.
References Camera::createCameras(), initGL(), initializeGL(), m_cam, m_camera, m_drawGrid, m_drawNormals, Camera::m_mainCamera, m_meshLoc, m_normalSize, m_parser, m_rotate, m_shaderManager, m_shapeType, m_spinXFace, m_spinYFace, m_spinZFace, m_toggleAxis, m_toggleObj, m_window, and m_wireframe.
  : QOpenGLWidget(_parent)
{
  // re-size the widget to that of the parent (in that case the GLFrame passed in on construction)
  m_rotate=false;
  // mouse rotation values set to 0
  m_spinXFace = 0.0f;
  m_spinYFace = 0.0f;
  m_spinZFace = 0.0;
  m_parser= _libParent; //DONT CHANGE THIS
  m_shapeType=6;
  m_toggleObj=false;
  m_toggleAxis=false;
  m_meshLoc="./models/Suzanne.obj";
  m_drawNormals=false;
  m_drawGrid=false;
  m_normalSize=0.1;
  // Store main window to send data from compile errors
  m_window = dynamic_cast<MainWindow*>(_parent);
  // re-size the widget to that of the parent (in this case the GLFrame passed in on construction)
  this->resize(_parent->size());
  m_wireframe=false;
  m_shaderManager = _manager;
  m_camera = new Camera();
  m_camera->createCameras();
  m_cam = m_camera->m_mainCamera;
  // set this widget to have the initial keyboard focus
  setFocus();
  connect(this, SIGNAL(initializeGL()), this, SLOT(initGL()));
}
NGLScene::~NGLScene ()
dtor must close down ngl and release OpenGL resources
Definition at line 64 of file NGLScene.cpp.
References m_parser, m_shaderManager, and m_textureName.
{
  //delete m_readFromXML;
  delete m_parser;
  delete m_shaderManager;
  //Clear any existing texture maps
  glDeleteTextures(1,&m_textureName);
}
Member Function Documentation
void NGLScene::compileShader (QString _vertSource, QString _fragSource)
loads and compiles a shader from Qstrings passed from the text editor
Parameters
in _vertSource the Qstring containing the vertex shader source code
in _fragSource the Qstring containing the fragment shader source code
Definition at line 562 of file NGLScene.cpp.
References ParserLib::assignAllData(), ShaderManager::compileShader(), ShaderManager::getErrorLog(), m_parser, m_shaderManager, m_window, parseErrorLog(), and MainWindow::setTerminalText().
{
  m_shaderManager->compileShader(_vertSource, _fragSource);
  m_window->setTerminalText(parseErrorLog(m_shaderManager->getErrorLog()));
  update();
  m_parser->assignAllData();
}
void NGLScene::createCamera () [private]
set the camera shape in the scene
void NGLScene::createLineMarker (QString _shaderName, int _lineNum) [signal]
signal to create a line marker
Parameters
in _shaderName the shader name of the error in the GLSL file
in _lineNum the line number of the error in the GLSL file
void NGLScene::drawAxis (ngl::Vec3 _pos) [private]
Draw a xyz axis.
Parameters
_pos is the position that the axis is drawn relative to the origin
Definition at line 687 of file NGLScene.cpp.
References loadMatricesToShader(), m_shaderManager, m_transform, and ShaderManager::use().
{
  // Instance the Shader
  ngl::ShaderLib *shaderLib=ngl::ShaderLib::instance();
  m_shaderManager->use(0);
  ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
  // Move the Y AXIS geo
  m_transform.setScale(0.05,0.5,0.05);
  m_transform.setPosition(0,0.3,0);
  m_transform.addPosition(_pos);
  loadMatricesToShader();
  shaderLib->setShaderParam4f("Colour",0,1,0,1); //Not entirely sure if this is the best way, as the name
       "Colour" could be changed....
  prim->draw("cube");
  m_transform.reset();
  // Move the X AXIS geo
  m_transform.setScale(0.5,0.05,0.05);
  m_transform.setPosition(0.3,0,0);
  m_transform.addPosition(_pos);
  loadMatricesToShader();
  shaderLib->setShaderParam4f("Colour",1,0,0,1); //Not entirely sure if this is the best way, as the name
       "Colour" could be changed....
  prim->draw("cube");
  m_transform.reset();
  // Move the Z AXIS geo
  m_transform.setScale(0.05,0.05,0.5);
  m_transform.setPosition(0,0,0.3);
  m_transform.addPosition(_pos);
  loadMatricesToShader();
  shaderLib->setShaderParam4f("Colour",0,0,1,1); //Not entirely sure if this is the best way, as the name
       "Colour" could be changed....
  prim->draw("cube");
  m_transform.reset();
}
void NGLScene::drawObject (uint _type) [private]
draw an object based on the m_shapeType; e.g. 0=mesh, 1=sphere, etc
Definition at line 318 of file NGLScene.cpp.
References m_mesh.
{
  ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
  enum geo {input=0,sphere=1,cube=2,torus=3,teapot=4,troll=5,dragon=6,bunny=7};
  // Draw different objects depending on the input value
  switch(_type)
  {
  case input : { m_mesh->draw(); break; }
  case sphere: { prim->draw("sphere");break; }
  case cube : { prim->draw("cube"); break; }
  case torus : { prim->draw("torus"); break; }
  case teapot: { prim->draw("teapot");break; }
  case troll : { prim->draw("troll"); break; }
  case dragon: { prim->draw("dragon");break; }
  case bunny : { prim->draw("bunny"); break; }
  default : std::cerr<<"unrecognised shape type value\n"; break;
  }
}
void NGLScene::exportUniform () [slot]
exports the uniforms and writes them to the file ParsingOutput.txt
Definition at line 668 of file NGLScene.cpp.
References ParserLib::exportUniforms(), m_parser, and m_window.
{
  QString fileName = QFileDialog::getSaveFileName(m_window,
                                                  tr("Export Uniforms"),
                                                  QDir::homePath(),
                                                  tr("Text File (*.txt)"));
  if (fileName != "")
  {
    if (m_parser->exportUniforms(fileName))
    {
      QMessageBox msgBox;
      msgBox.setText("Uniforms successfully exported");
      msgBox.setWindowTitle("Successfully Exported");
      msgBox.exec();
    }
  }
}
void NGLScene::importMeshName (const std::string & _name)
Changes the name of the m_mesh object directory.
Parameters
in the new directory used to draw m_mesh
Definition at line 93 of file NGLScene.cpp.
References m_toggleObj, setMeshLocation(), and setShapeType().
{
  // If the CANCEL button is clicked, then don't update the shapetype or location
  std::ifstream shaderSource(_name.c_str());
  if (!shaderSource.is_open())
  {
    if(_name.length()==0)
    {
      std::cerr<<"Import Cancelled"<<std::endl;
      //exit(EXIT_FAILURE);
    }
    else
    {
      std::cerr<<"File not found"<<_name.c_str()<<std::endl;
      //exit(EXIT_FAILURE);
    }
  }
  else
  {
    setMeshLocation(_name);
    setShapeType(0);
    m_toggleObj=true;
  }
}
void NGLScene::importTextureMap (const std::string & _name)
loads in a texture map and directly applies it to the OBJ. (Requires UVs)
Parameters
in the desired directory of the texture map
Definition at line 121 of file NGLScene.cpp.
References m_textureName.
{
  std::ifstream textureSource(_name.c_str());
  ngl::Texture texture (_name);
  m_textureName=texture.setTextureGL();
  update();
}
void NGLScene::initGL () [slot]
the initialize class is called once when the window is created and we have a valid GL context use this to setup any default GL stuff
Definition at line 135 of file NGLScene.cpp.
References clearAllGlErrors(), ShaderManager::compileStatus(), ShaderManager::getErrorLog(), ShaderManager::initialize(), ShaderManager::isInit(), m_cam, m_mesh, m_meshLoc, m_shaderManager, m_textureName, m_window, parseErrorLog(), and MainWindow::setTerminalText().
{
  ngl::NGLInit::instance();
  clearAllGlErrors();
  glClearColor(0.4f, 0.4f, 0.4f, 1.0f); // Grey Background
  // enable depth testing for drawing
  glEnable(GL_DEPTH_TEST);
  // enable multisampling for smoother drawing
  glEnable(GL_MULTISAMPLE);
  // now to load the shader and set the values
  // grab an instance of shader manager
  m_shaderManager->initialize();
  ngl::Texture texture ("textures/metalTexture.jpg");
  m_textureName=texture.setTextureGL();
  if(!m_shaderManager->compileStatus())
  {
    m_window->setTerminalText(parseErrorLog(m_shaderManager->getErrorLog()));
  }
  if(m_shaderManager->isInit())
  {
    ngl::Mat4 iv=m_cam.getViewMatrix();
    iv.transpose();
    //m_parser->assignAllData();
  }
  // Create mesh VAO
  m_mesh = std::unique_ptr<ngl::Obj> (new ngl::Obj(m_meshLoc));
  m_mesh->createVAO();
  // Create some default shapes
  ngl::VAOPrimitives::instance()->createSphere("sphere",0.7,30);
  ngl::VAOPrimitives::instance()->createTorus("torus",0.3,0.7,20,20);
  ngl::VAOPrimitives::instance()->createLineGrid("Grid",10,10,10);
}
void NGLScene::initializeGL () [signal]
the signal for initialize GL
void NGLScene::keyPressEvent (QKeyEvent * _event) [private]
this method should be called every time a keyboard button is pressed. Inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 552 of file NGLScene.cpp.
{
  switch (_event->key())
  {
  default : break ;
  }
  update();
}
void NGLScene::loadMatricesToShader () [private]
method to load transform matrices to the shader
Definition at line 351 of file NGLScene.cpp.
References m_cam, m_mouseGlobalTX, m_parser, m_shaderManager, m_transform, ParserLib::sendUniformsToShader(), and ShaderManager::use().
{
  ngl::ShaderLib *shaderLib=ngl::ShaderLib::instance();
  m_shaderManager->use(0);
  ngl::Mat4 MV;
  ngl::Mat4 MVP;
  ngl::Mat3 normalMatrix;
  ngl::Mat4 M;
  M=m_transform.getMatrix()*m_mouseGlobalTX;
  MV= M*m_cam.getViewMatrix();
  MVP= M*m_cam.getVPMatrix();
  normalMatrix=MV;
  normalMatrix.inverse();
  m_parser->sendUniformsToShader(shaderLib);
  shaderLib->setShaderParamFromMat4("MV",MV);
  shaderLib->setShaderParamFromMat4("MVP",MVP);
  shaderLib->setShaderParamFromMat3("normalMatrix",normalMatrix);
  shaderLib->setShaderParamFromMat4("M",M);
}
void NGLScene::mouseMoveEvent (QMouseEvent * _event) [private]
this method is called every time a mouse is moved
Parameters
_event the Qt Event structure
Definition at line 410 of file NGLScene.cpp.
References INCREMENT, m_cameraIndex, m_modelPos, m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, m_spinXFace, m_spinYFace, m_spinZFace, and m_translate.
{
  if(m_rotate && _event->buttons() == Qt::LeftButton)
  {
    int diffx=_event->x()-m_origX;
    int diffy=_event->y()-m_origY;
    m_origX = _event->x();
    m_origY = _event->y();
    // Changes viewport rotation depending on camera view.
    switch(m_cameraIndex){
      case 0:
        m_spinZFace -= (float) 0.5f * diffy;
        m_spinXFace += (float) 0.5f * diffy;
        m_spinYFace += (float) 1.0f * diffx;
        break;
      case 1:
        m_spinXFace -= diffy;
        m_spinZFace += diffx; break;
      case 2:
        m_spinXFace += diffy;
        m_spinZFace += diffx; break;
      case 3:
        m_spinXFace -= diffy;
        m_spinYFace += diffx; break;
      case 4:
        m_spinXFace += diffy;
        m_spinYFace += diffx; break;
    }
    update();
  }
  else if(m_translate && _event->buttons() == Qt::RightButton)
  {
    int diffX = (int)(_event->x() - m_origXPos);
    int diffY = (int)(_event->y() - m_origYPos);
    m_origXPos=_event->x();
    m_origYPos=_event->y();
    // Switch used to change how modelPos translates depending on camera.
    switch(m_cameraIndex){
    case 0:
        m_modelPos.m_y -= INCREMENT * diffY;
        m_modelPos.m_x += INCREMENT * diffY/2;
        m_modelPos.m_z += INCREMENT * diffY/2;
        m_modelPos.m_x += INCREMENT * diffX/2;
        m_modelPos.m_z -= INCREMENT * diffX/2; break;
    case 1:
        m_modelPos.m_z -= INCREMENT * diffY;
        m_modelPos.m_x -= INCREMENT * diffX;break;
    case 2:
        m_modelPos.m_z -= INCREMENT * diffY;
        m_modelPos.m_x += INCREMENT * diffX;break;
    case 3:
        m_modelPos.m_x -= INCREMENT * diffX;
        m_modelPos.m_y -= INCREMENT * diffY;break;
    case 4:
        m_modelPos.m_x += INCREMENT * diffX;
        m_modelPos.m_y -= INCREMENT * diffY;break;
    }
    update();
  }
}
void NGLScene::mousePressEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is pressed inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 475 of file NGLScene.cpp.
References m_origX, m_origXPos, m_origY, m_origYPos, m_rotate, and m_translate.
{
  // left mouse rotate mode
  if(_event->button() == Qt::LeftButton)
  {
    m_origX = _event->x();
    m_origY = _event->y();
    m_rotate =true;
  }
  // right mouse translate mode
  else if(_event->button() == Qt::RightButton)
  {
    m_origXPos = _event->x();
    m_origYPos = _event->y();
    m_translate=true;
  }
  update();
}
void NGLScene::mouseReleaseEvent (QMouseEvent * _event) [private]
this method is called everytime the mouse button is released inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 496 of file NGLScene.cpp.
References m_rotate, and m_translate.
{
  // that event is called when the mouse button is released
  // we then set Rotate to false
  if (_event->button() == Qt::LeftButton)
  {
    m_rotate=false;
  }
  // right mouse translate mode
  if (_event->button() == Qt::RightButton)
  {
    m_translate=false;
  }
}
void NGLScene::objectTransform (uint _type) [private]
Set object transformations depending on the shape type.
Parameters
_event the Qt Event structure
Definition at line 277 of file NGLScene.cpp.
References loadMatricesToShader(), and m_transform.
{
  enum geo {input=0,sphere=1,cube=2,torus=3,teapot=4,troll=5,dragon=6,bunny=7};
  // Transform differently depending on the object being drawn
  // Used to make all default shapes a similar size
  switch(_type)
  {
  case input : break;
  case sphere: break;
  case cube : break;
  case torus : break;
  case teapot: break;
  case troll :
  {
    m_transform.setScale(1.5,1.5,1.5);
    loadMatricesToShader();
    break;
    // Moved the troll to be the same relative shape and position
  }
  case dragon:
  {
    m_transform.setScale(0.1,0.1,0.1);
    m_transform.setPosition(0,-0.5,0);
    loadMatricesToShader();
    break;
    // Moved the dragon to be the same relative shape and position
  }
  case bunny:
  {
    m_transform.setScale(0.15,0.15,0.15);
    m_transform.setPosition(0,-0.5,0);
    loadMatricesToShader();
    break;
    // Moved the bunny to be the same relative shape and position
  }
  default: std::cerr<<"unrecognised shape type value\n"; break;
  }
}
void NGLScene::paintGL ()
this is called everytime we want to draw the scene
Definition at line 194 of file NGLScene.cpp.
References drawAxis(), drawObject(), loadMatricesToShader(), Camera::m_aspect, m_cam, m_camera, Camera::m_cameraIndex, m_cameraIndex, m_drawGrid, m_drawNormals, Camera::m_mainCamera, m_modelPos, m_mouseGlobalTX, m_normalSize, m_shaderManager, m_shapeType, m_spinXFace, m_spinYFace, m_spinZFace, m_textureName, m_toggleAxis, m_toggleObj, m_transform, m_wireframe, objectTransform(), Camera::setShapeCam(), toggleObj(), and ShaderManager::use().
{
  glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
  if(m_wireframe == true)
  {
    glPolygonMode(GL_FRONT_AND_BACK,GL_LINE);
  }
  else
  {
    //glBindTexture(GL_TEXTURE_2D, m_textureName);
    glPolygonMode(GL_FRONT_AND_BACK,GL_FILL);
  }
  ngl::ShaderLib *shaderLib=ngl::ShaderLib::instance();
  m_shaderManager->use(0);
  // Rotation based on the mouse position for our global transform
  ngl::Mat4 rotX;
  ngl::Mat4 rotY;
  ngl::Mat4 rotZ;
  // create the rotation matrices
  rotX.rotateX(m_spinXFace);
  rotY.rotateY(m_spinYFace);
  rotZ.rotateZ(m_spinZFace);
  // multiply the rotations
  m_mouseGlobalTX=rotY*rotX*rotZ;
  // add the translations
  m_mouseGlobalTX.m_m[3][0] = m_modelPos.m_x;
  m_mouseGlobalTX.m_m[3][1] = m_modelPos.m_y;
  m_mouseGlobalTX.m_m[3][2] = m_modelPos.m_z;
  //draw initial texture map
  glBindTexture(GL_TEXTURE_2D, m_textureName);
  m_shaderManager->use(0);
  ngl::VAOPrimitives *prim=ngl::VAOPrimitives::instance();
  m_camera->m_aspect = (float)width()/height();
  m_camera->setShapeCam();
  m_cam = m_camera->m_mainCamera;
  m_cameraIndex = m_camera->m_cameraIndex;
  m_transform.reset();
  if (m_toggleAxis)
  {
    ngl::Vec3 pos={-1,-0.5,-1};
    drawAxis(pos);
  }
  loadMatricesToShader();
  if (m_drawGrid)
  {
    // Draw a grid
    prim->draw("Grid");
  }
  if (m_toggleObj)
  {
    // Activate Obj
    toggleObj();
  }
  // Set object transformation and draw
  objectTransform(m_shapeType);
  drawObject(m_shapeType);
  if(m_drawNormals)
  {
    // set the shader to use the normalShader
    m_shaderManager->use(1);
    ngl::Mat4 MV;
    ngl::Mat4 MVP;
    MV=m_transform.getMatrix()*m_mouseGlobalTX*m_cam.getViewMatrix();
    MVP=MV*m_cam.getProjectionMatrix();
    // set the uniform to use the current transformations
    shaderLib->setUniform("MVP",MVP);
    // set the normalSize
    shaderLib->setUniform("normalSize",m_normalSize);
    //draw the object normals
    drawObject(m_shapeType);
  }
}
QString NGLScene::parseErrorLog (QString _string) [private]
Stores a QString. Used to edit the error log message.
Definition at line 572 of file NGLScene.cpp.
References createLineMarker().
{
  // Declare a string to output
  // And a list of integer to be used for line error highlighting
  QString outputErrors;
  QString shaderName;
  // Separate the input _string into separate lines.
  QRegExp separateLines("\n");
  QStringList lines=_string.split(separateLines);
  for (int i=0;i<lines.length();i++)
  {
    // Split each line using braces; "(" and ")"
    QRegExp separateNumbers("(\\(|\\))");
    QStringList pieces=lines.value(i).split(separateNumbers);
    for (int j=0;j<pieces.length();j++)
    {
      // This is the how to get the Title (Shader file)
      if (pieces.length()==1 && pieces[j]!="")
      {
        // Split the line using the "Remove Colon"
        if(pieces.value(j).endsWith("Vertex:"))
        {
          shaderName=QString("Vertex");
        }
        if(pieces.value(j).endsWith("Fragment:"))
        {
          shaderName=QString("Fragment");
        }
      }
      // If the first segment of the line is 0...
      // remove it and replace it with "Line"
      if(pieces[j].length()==1 && j==0)
      {
        outputErrors.append("Line ");
      }
      // Add the rest of the string to the list
      else
      {
        outputErrors.append(pieces.value(j));
        // Add the second part of the line fragment as that is the line error number.
        // This can be returned as a list of integers
        if (j==1)
        {
          int lineNumber = pieces.value(j).toInt();
          emit createLineMarker(shaderName,lineNumber-1);
        }
      }
    }
    // If it is the last line, add a new line to the string
    int finalLine =lines.length()-1;
    if (i!=finalLine)
    {
      outputErrors.append("\n");
    }
  }
  return outputErrors;
}
void NGLScene::resetObjPos () [slot]
resets the position of the active OBJ in the OpenGL context
Definition at line 639 of file NGLScene.cpp.
References Camera::cameraPitch(), Camera::cameraRoll(), Camera::cameraYaw(), m_camera, Camera::m_farClip, Camera::m_fov, m_modelPos, Camera::m_nearClip, m_spinXFace, m_spinYFace, and m_spinZFace.
{
  //move camera back to default
  m_modelPos.m_x = 0;
  m_modelPos.m_y = 0;
  m_modelPos.m_z = 0;
  m_spinXFace = 0;
  m_spinYFace = 0;
  m_spinZFace = 0;
  m_camera->cameraRoll(0.00);
  m_camera->cameraYaw(0.00);
  m_camera->cameraPitch(0.00);
  m_camera->m_fov = 60.0;
  m_camera->m_nearClip = 0.5;
  m_camera->m_farClip = 150.0;
  update();
}
void NGLScene::resizeGL (QResizeEvent * _event)
this is called everytime we resize the scene note: Qt 5.5.1 must have this implemented and uses it
Parameters
in _event the Qt Event structure
Definition at line 339 of file NGLScene.cpp.
References Camera::m_aspect, and m_camera.
{
  m_camera->m_aspect = (float)width()/height();
}
void NGLScene::resizeGL (int _w, int _h)
this is called everytime we resize the scene note: Qt 5.x uses this instead! http://doc.qt.io/qt-5/qopenglwindow.html#resizeGL
Parameters
in _event the Qt Event structure
Definition at line 345 of file NGLScene.cpp.
References Camera::m_aspect, and m_camera.
{
  m_camera->m_aspect = (float)width()/height();
}
void NGLScene::setMeshLocation (std::string _meshDirectory)
sets the file location you of a mesh
Definition at line 75 of file NGLScene.cpp.
References m_meshLoc.
{
  m_meshLoc=_meshDirectory;
  //std::cout<<"Imported file: "<<_meshDirectory<<std::endl;
}
void NGLScene::setNormalSize (int _size) [slot]
sets the normal size
Parameters
in _size the normal size.....the normal size will be divided by 100
Definition at line 403 of file NGLScene.cpp.
References m_normalSize.
{
  m_normalSize=_size/100.0f;
  update();
}
void NGLScene::setProject (std::string _name, QString _vertSource, QString _fragSource)
Creates a new project for the shader.
Parameters
in _name the name of the project
in _vertSource the text that makes of the vertex shader
in _fragSource The text that makes up the fragment shader
Definition at line 661 of file NGLScene.cpp.
References compileShader(), ShaderManager::createShaderProgram(), and m_shaderManager.
{
  m_shaderManager->createShaderProgram(_name);
  compileShader(_vertSource, _fragSource);
}
void NGLScene::setShapeType (int _type) [slot]
sets the shape type
Parameters
in _type is the type of object drawn
Definition at line 177 of file NGLScene.cpp.
References m_shapeType.
{
  if (_type<=7 && _type>=0)
  {
    m_shapeType=_type;
  }
  else
  {
    //std::cout<<"Invalid shape type"<<std::endl;
  }
  update();
}
void NGLScene::toggleAxis (bool _state) [slot]
toggles the axis visibility
Parameters
in _state true=on false=off
Definition at line 396 of file NGLScene.cpp.
References m_toggleAxis.
{
  m_toggleAxis=_state;
  update();
}
void NGLScene::toggleGrid (bool _state) [slot]
toggles the grid visibility
Parameters
in _state true=on false=off
Definition at line 389 of file NGLScene.cpp.
References m_drawGrid.
{
  m_drawGrid=_state;
  update();
}
void NGLScene::toggleNormals (bool _state) [slot]
toggles the normals visibility
Parameters
in _state true=on false=off
Definition at line 382 of file NGLScene.cpp.
References m_drawNormals.
{
  m_drawNormals=_state;
  update();
}
void NGLScene::toggleObj () [private]
Activate the m_mesh .obj.
Definition at line 81 of file NGLScene.cpp.
References m_mesh, m_meshLoc, and m_toggleObj.
{
  if(m_toggleObj==true)
  {
    m_mesh = std::unique_ptr<ngl::Obj> (new ngl::Obj(m_meshLoc));
    m_mesh->createVAO();
    m_toggleObj=false;
  }
}
void NGLScene::toggleWireframe (bool _state) [slot]
toggles the wireframe visibility
Parameters
in _state true=on false=off
Definition at line 375 of file NGLScene.cpp.
References m_wireframe.
{
  m_wireframe=_state;
  update();
}
void NGLScene::wheelEvent (QWheelEvent * _event) [private]
this method is called everytime the mouse wheel is moved inherited from QObject and overridden here.
Parameters
_event the Qt Event structure
Definition at line 512 of file NGLScene.cpp.
References m_cameraIndex, m_modelPos, and ZOOM.
{
  // check the diff of the wheel position (0 means no change)
  if(_event->delta() > 0)
  {
    switch(m_cameraIndex){
    case 0:
      m_modelPos.m_z+=ZOOM;
      m_modelPos.m_x+=ZOOM; break;
    case 1:
      m_modelPos.m_y+=ZOOM; break;
    case 2:
      m_modelPos.m_y-=ZOOM; break;
    case 3:
      m_modelPos.m_z-=ZOOM; break;
    case 4:
      m_modelPos.m_z+=ZOOM; break;
    }
  }
  else if(_event->delta() < 0)
  {
    switch(m_cameraIndex){
    case 0:
      m_modelPos.m_z-=ZOOM;
      m_modelPos.m_x-=ZOOM; break;
    case 1:
      m_modelPos.m_y-=ZOOM; break;
    case 2:
      m_modelPos.m_y+=ZOOM; break;
    case 3:
      m_modelPos.m_z+=ZOOM; break;
    case 4:
      m_modelPos.m_z-=ZOOM; break;
    }
  }
  update();
}
Member Data Documentation
ngl::Camera NGLScene::m_cam [private]
The camera.
Definition at line 245 of file NGLScene.h.
Camera* NGLScene::m_camera
Pointer to inherit camera class. This is public for signal/slot access.
Definition at line 72 of file NGLScene.h.
int NGLScene::m_cameraIndex [private]
An index to access the cameras.
Definition at line 306 of file NGLScene.h.
bool NGLScene::m_drawGrid [private]
A toggle used to draw a grid.
Definition at line 285 of file NGLScene.h.
bool NGLScene::m_drawNormals [private]
A toggle used to draw normals.
Definition at line 281 of file NGLScene.h.
std::unique_ptr<ngl::Obj> NGLScene::m_mesh [private]
Pointer to the VAO m_mesh.
Definition at line 314 of file NGLScene.h.
std::string NGLScene::m_meshLoc [private]
A string to store the .obj m_mesh directory.
Definition at line 310 of file NGLScene.h.
ngl::Vec3 NGLScene::m_modelPos [private]
the model position for mouse movement
Definition at line 249 of file NGLScene.h.
ngl::Mat4 NGLScene::m_mouseGlobalTX [private]
used to store the global mouse transforms
Definition at line 241 of file NGLScene.h.
float NGLScene::m_normalSize [private]
Stores the size of the normal.
Definition at line 289 of file NGLScene.h.
int NGLScene::m_origX [private]
the previous x mouse value
Definition at line 225 of file NGLScene.h.
int NGLScene::m_origXPos [private]
the previous x mouse value for Position changes
Definition at line 233 of file NGLScene.h.
int NGLScene::m_origY [private]
the previous y mouse value
Definition at line 229 of file NGLScene.h.
int NGLScene::m_origYPos [private]
the previous y mouse value for Position changes
Definition at line 237 of file NGLScene.h.
ParserLib* NGLScene::m_parser
the parser to deal with all the uniform values stored in the shader
Todo
Todo Should be private and have get method
Definition at line 67 of file NGLScene.h.
IO_XML* NGLScene::m_readFromXML [private]
read from xml file
Definition at line 261 of file NGLScene.h.
bool NGLScene::m_rotate [private]
flag to indicate if the mouse button is pressed when dragging
Definition at line 201 of file NGLScene.h.
ngl::Vec3 NGLScene::m_rotation [private]
rotation of the teapot
Definition at line 217 of file NGLScene.h.
bool NGLScene::m_shaderError [private]
If there is a shader error or not.
Definition at line 297 of file NGLScene.h.
ShaderManager* NGLScene::m_shaderManager [private]
Stores the shader manager which handles the setup and maintenance of shaders.
Definition at line 302 of file NGLScene.h.
uint NGLScene::m_shapeType [private]
defines the mesh type
Definition at line 269 of file NGLScene.h.
int NGLScene::m_spinXFace [private]
used to store the x rotation mouse value
Definition at line 205 of file NGLScene.h.
int NGLScene::m_spinYFace [private]
used to store the y rotation mouse value
Definition at line 209 of file NGLScene.h.
int NGLScene::m_spinZFace [private]
used to store the z rotation mouse value
Definition at line 213 of file NGLScene.h.
GLuint NGLScene::m_textureName [private]
stores the texture name
Definition at line 293 of file NGLScene.h.
bool NGLScene::m_toggleAxis [private]
A toggle used to turn axis on and off.
Definition at line 277 of file NGLScene.h.
bool NGLScene::m_toggleObj [private]
A toggle used to import the .obj m_mesh.
Definition at line 273 of file NGLScene.h.
ngl::Transformation NGLScene::m_transform [private]
transformation stack for the gl transformations etc
Definition at line 253 of file NGLScene.h.
bool NGLScene::m_translate [private]
flag to indicate if the Right mouse button is pressed when dragging
Definition at line 221 of file NGLScene.h.
MainWindow* NGLScene::m_window [private]
the main window that is the GUI
Definition at line 265 of file NGLScene.h.
bool NGLScene::m_wireframe [private]
set the view to show wireframe
Definition at line 257 of file NGLScene.h.
The documentation for this class was generated from the following files:
NGLScene.h
NGLScene.cpp