Project Class Reference
stores the name and directory of the current project as well as
#include <Project.h>
Public Member Functions
Project ()
default constructor for project class
~Project ()
default destructor for the project class
void set (std::string _name, std::string _dir, bool _saveState, bool _firstSave)
method to set the data for the project
bool save (QString _vertSource, QString _fragSource)
method for saving the current project
bool saveAs (QString _vertSource, QString _fragSource)
method for saving the current project as a new project
void load (std::string _loadedFileDirectory, QString &o_vertSource, QString &o_fragSource)
method to load in a project from an xml file
bool exportProject (std::string _targetDir, QString _vertSource, QString _fragSource)
method for exporting the vertex and fragment shaders
std::string getName ()
method to return the name of the current project
std::string getDir ()
method to return the directory of the current project
int confirmOverwrite (QString _filePath)
method to confirm overwriting exported files
Private Attributes
std::string m_projectName
the name of the current project
std::string m_projectDir
the directory of the current project
bool m_saved
flag storing whether the current project has been previously saved
bool m_firstSave
flag storing whether the current project is being saved for the first time
IO_XML * m_xml
used to save and load project information from xml file
Detailed Description
stores the name and directory of the current project as well as
providing methods for saving and loading projects to xml files and exporting the porject's shaders to glsl files.
Definition at line 26 of file Project.h.
Constructor & Destructor Documentation
Project::Project ()
default constructor for project class
Definition at line 13 of file Project.cpp.
References m_firstSave, m_projectDir, m_projectName, m_saved, and m_xml.
{
  m_projectName = "untitled";
  m_projectDir = "";
  m_xml = new IO_XML;
  m_saved = false;
  m_firstSave = true;
}
Project::~Project ()
default destructor for the project class
Definition at line 24 of file Project.cpp.
References m_xml.
{
  delete m_xml;
}
Member Function Documentation
int Project::confirmOverwrite (QString _filePath)
method to confirm overwriting exported files
Parameters
in _filePath the path of the file to overwrite
Definition at line 88 of file Project.cpp.
{
  QMessageBox msgBox;
  msgBox.setIcon(QMessageBox::Warning);
  msgBox.setText("The file you have specified already exists: " + _filePath);
  msgBox.setInformativeText("Do you want to overwrite the file?");
  msgBox.setStandardButtons(QMessageBox::Save | QMessageBox::No | QMessageBox::Cancel);
  msgBox.setDefaultButton(QMessageBox::Save);
  int ret = msgBox.exec();
  return ret;
}
bool Project::exportProject (std::string _targetDir, QString _vertSource, QString _fragSource)
method for exporting the vertex and fragment shaders
from the current project for GLSL files
Parameters
_targetDir the directory to save the GLSL files in
_vertSource the vertex shader source code to save
_fragSource the fragment shader source code to save
Definition at line 102 of file Project.cpp.
References confirmOverwrite(), m_projectName, and CEBRaise::QtFileError().
{
  _targetDir.append("/");
  QString detOutput;
  //create path to vertex.glsl in target directory
  QString vFilePath = QString::fromStdString(_targetDir + m_projectName + "Vertex.glsl");
  qDebug() << vFilePath;
  //create qfile object assiciated with the file name
  QFile vertFile(vFilePath);
  QFileInfo checkPath(vFilePath);
  int state = QMessageBox::Save;
  if (checkPath.exists() && checkPath.isFile())
  {
    state = confirmOverwrite(vFilePath);
    if (state == QMessageBox::Cancel)
    {
      return false;
    }
  }
  if (state == QMessageBox::Save)
  {
    //try to open the file for writing, if it doesnt exist the open() method will create it.
    if(!vertFile.open(QIODevice::WriteOnly | QIODevice::Text))
    {
      CEBRaise::QtFileError(vertFile.error(), vFilePath);
      return false;
    }
    // write vertex source into Vertex.glsl file
    QTextStream outVert(&vertFile);
    outVert << _vertSource;
    vertFile.close();
    detOutput.append("Vertex File: " + vFilePath + "\n");
  }
  //now do the same for fragment.glsl
  QString fFilePath = QString::fromStdString(_targetDir + m_projectName + "Fragment.glsl");
  qDebug() << fFilePath;
  QFile fragFile(fFilePath);
  checkPath = QFileInfo(fFilePath);
  state = QMessageBox::Save;
  if (checkPath.exists() && checkPath.isFile())
  {
    state = confirmOverwrite(fFilePath);
    if (state == QMessageBox::Cancel)
    {
      return false;
    }
  }
  if (state == QMessageBox::Save)
  {
    if(!fragFile.open(QIODevice::WriteOnly | QIODevice::Text))
    {
      CEBRaise::QtFileError(fragFile.error(), fFilePath);
      return false;
    }
    QTextStream outFrag(&fragFile);
    outFrag << _fragSource;
    fragFile.close();
    detOutput.append("Fragment File: " + vFilePath + "\n");
  }
  QMessageBox msgBox;
  msgBox.setText("The file(s) have been successfully saved");
  msgBox.setDetailedText(detOutput);
  msgBox.exec();
  return true;
}
std::string Project::getDir () [inline]
method to return the directory of the current project
Definition at line 87 of file Project.h.
References m_projectDir.
{return m_projectDir;}
std::string Project::getName () [inline]
method to return the name of the current project
Definition at line 83 of file Project.h.
References m_projectName.
{return m_projectName;}
void Project::load (std::string _loadedFileDirectory, QString & o_vertSource, QString & o_fragSource)
method to load in a project from an xml file
Parameters
_loadedFileDirectory the directory of the loaded file
o_vertSource output vertex shader source code from loaded project
o_fragSource output fragment shader source code from loaded project
Definition at line 181 of file Project.cpp.
References m_xml, IO_XML::readProjectXML(), and set().
{
  std::cout<<"Opening: "<<_loadedFileDirectory<<std::endl;
  std::string vertSource = "";
  std::string fragSource = "";
  std::string fileName = "";
  std::string fileDirectory = "";
  // read project from XML file storing data in variables.
  m_xml->readProjectXML(fileName, fileDirectory, _loadedFileDirectory, vertSource, fragSource);
  // set the project data
  set(fileName, fileDirectory, true, false);
  // set output shader source strings
  o_vertSource = QString::fromStdString(vertSource);
  o_fragSource = QString::fromStdString(fragSource);
}
bool Project::save (QString _vertSource, QString _fragSource)
method for saving the current project
Parameters
_vertSource the vertex shader source code to save
_fragSource the fragment shader source code to save
Definition at line 31 of file Project.cpp.
References m_firstSave, m_projectDir, m_projectName, m_saved, m_xml, set(), and IO_XML::writeProject().
{
  QString fileName;
  // if the project has not been saved before then open the QFile Dialog
  if(!m_saved)
  {
    QFileDialog dialog;
    dialog.setFileMode(QFileDialog::AnyFile);
    dialog.setAcceptMode(QFileDialog::AcceptSave);
    if (dialog.exec())
    {
      fileName = dialog.selectedFiles().at(0);
      QFileInfo finfo = QFileInfo(fileName);
      // set project data fromt eh dialog and set m_saved to true
      set(finfo.baseName().toStdString(), finfo.absolutePath().toStdString(), true, true);
    }
    else
    {
      return false;
    }
  }
  std::cout<<"Saving project..."<<std::endl;
  // convert QStrings to c strings.
  std::string vertSourceString = _vertSource.toStdString();
  std::string fragSourceString = _fragSource.toStdString();
  const char * vertSource_c = vertSourceString.c_str();
  const char * fragSource_c = fragSourceString.c_str();
  //write project to XML
  bool success = m_xml->writeProject(m_projectName, m_projectDir, vertSource_c,
                                     fragSource_c, !m_firstSave);
  if (success)
  {
    std::cout<<"Saved project: \nName: "<<m_projectName<<" Directory: "<<
      m_projectDir<<std::endl;
    m_firstSave=false;
  }
  return success;
}
bool Project::saveAs (QString _vertSource, QString _fragSource)
method for saving the current project as a new project
Parameters
_vertSource the vertex shader source code to save
_fragSource the fragment shader source code to save
Definition at line 79 of file Project.cpp.
References m_saved, and save().
{
  // set save state to false then call save function
  m_saved = false;
  return save(vertSource, _fragSource);
}
void Project::set (std::string _name, std::string _dir, bool _saveState, bool _firstSave) [inline]
method to set the data for the project
Parameters
_name the name of the project
_dir the directory of the project
_saveState flag for whether the project has previsouly been saved
Definition at line 45 of file Project.h.
References m_firstSave, m_projectDir, m_projectName, and m_saved.
  {
    m_projectName = _name;
    m_projectDir = _dir;
    m_saved = _saveState;
    m_firstSave = _firstSave;
  }
Member Data Documentation
bool Project::m_firstSave [private]
flag storing whether the current project is being saved for the first time
Definition at line 111 of file Project.h.
std::string Project::m_projectDir [private]
the directory of the current project
Definition at line 102 of file Project.h.
std::string Project::m_projectName [private]
the name of the current project
Definition at line 98 of file Project.h.
bool Project::m_saved [private]
flag storing whether the current project has been previously saved
Definition at line 106 of file Project.h.
IO_XML* Project::m_xml [private]
used to save and load project information from xml file
Definition at line 115 of file Project.h.
The documentation for this class was generated from the following files:
Project.h
Project.cpp